/*
 * NIMCET syllabus data.
 *
 * Structure: SUBJECT -> CHAPTER -> TOPIC -> SUBTOPIC (leaf).
 * Leaf tuple: [name, w, d, need, skip, tip]
 *   w    = estimated questions per paper (from PYQ trends, NOT official)
 *   d    = depth level 1/2/3 (see DEPTH below)
 *   need = exactly what must be covered
 *   skip = what is NOT needed for NIMCET (don't waste time)
 *   tip  = speed trick / shortcut (optional)
 *
 * Question targets and time budgets are computed from w and d in engine.js.
 */

const DEPTH = {
  1: {
    label: "D1 · Basic",
    short: "Basic",
    text: "Formula + direct questions. NCERT level. Proofs/derivations nahi. 1 line me concept samajh aana chahiye.",
    think: 2,
  },
  2: {
    label: "D2 · Standard",
    short: "Standard",
    text: "NCERT + objective moderate. 3–5 standard question types + unke shortcuts pakke. JEE Main easy-moderate level.",
    think: 5,
  },
  3: {
    label: "D3 · Deep",
    short: "Deep",
    text: "Multi-concept, tricky PYQs. Har question type, edge case aur shortcut. JEE Main level (JEE Advanced nahi).",
    think: 8,
  },
};

const BOOKS = {
  ncert: "NCERT",
  obj: "RD Sharma Objective Mathematics",
  rsaVR: "R.S. Aggarwal – A Modern Approach to Verbal & Non-Verbal Reasoning",
  rsaQA: "R.S. Aggarwal – Quantitative Aptitude",
  comp: "Claude notes + M. Morris Mano – Digital Design (Ch 1–4 selected)",
  eng: "Word Power Made Easy (vocab) + Wren & Martin (selected grammar)",
  pyq: "NIMCET PYQs (topic-wise, older years)",
};

const SUBJECTS = [
  { id: "M", name: "Mathematics", qs: 50, plus: 12, minus: 3, time: 70, color: "#4f7cff" },
  { id: "R", name: "Analytical Ability & Logical Reasoning", qs: 40, plus: 6, minus: 1.5, time: 30, color: "#16a37f" },
  { id: "C", name: "Computer Awareness", qs: 20, plus: 6, minus: 1.5, time: 20, color: "#d9822b", shareTimeWith: "E" },
  { id: "E", name: "General English", qs: 10, plus: 4, minus: 1, time: 0, color: "#b35fd6" },
];

// Chapters are listed in STUDY ORDER (prerequisites first, high weightage early).
const CHAPTERS = [
  /* ============================ MATHEMATICS ============================ */
  {
    id: "M01", subject: "M", name: "Sets, Relations & Functions",
    ncert: "NCERT 11 Ch 1 (Sets), 11 Ch 2 + 12 Ch 1 (Relations & Functions)",
    obj: "RD Sharma Objective: Sets; Relations; Functions",
    prereq: ["Number line & intervals notation [a,b), (a,∞)", "Basic inequalities solving", "Graphs of y=x, x², |x|, 1/x, √x"],
    speed: [
      "Venn diagram hamesha draw karo — 3-set questions me regions (a,b,c,d,e,f,g) likh ke solve karo.",
      "Counting formulas yaad: relations on n elements = 2^(n²), reflexive = 2^(n²−n), symmetric = 2^(n(n+1)/2).",
      "Domain questions: denominator ≠ 0, √(…) ≥ 0, log(…) > 0 — teeno conditions ek saath likho.",
    ],
    topics: [
      { name: "Sets", leaves: [
        ["Set basics, types, subsets & power set", 0.3, 1,
          "Roster/set-builder, empty/finite/infinite, subset count 2ⁿ, proper subsets 2ⁿ−1, power set.",
          "Axiomatic set theory, Russell paradox, proofs.",
          "n elements → subsets 2ⁿ, non-empty proper 2ⁿ−2."],
        ["Set operations, Venn diagrams & n(A∪B∪C)", 0.6, 2,
          "Union, intersection, difference, complement, De Morgan laws, n(A∪B), n(A∪B∪C), 'only one / exactly two / none' word problems.",
          "Formal proofs of set identities.",
          "'Exactly two' = Σn(A∩B) − 3n(A∩B∩C). Regions method > formula."],
        ["Cartesian product", 0.2, 1,
          "A×B, n(A×B)=n(A)·n(B), ordered pairs, A×B ≠ B×A.",
          "Cartesian product of 3+ sets proofs.", ""],
      ]},
      { name: "Relations", leaves: [
        ["Types of relations (reflexive, symmetric, transitive, equivalence)", 0.6, 2,
          "Check each property on given relation quickly, equivalence classes, identity/universal/void relation.",
          "Partial order relations theory, lattices.",
          "Transitive check: sirf un pairs (a,b),(b,c) ko dekho jo chain banate hain."],
        ["Counting relations", 0.3, 2,
          "Total, reflexive, symmetric, reflexive+symmetric relations count; smallest equivalence relation containing given pairs.",
          "Counting transitive relations (no formula exists).",
          "Reflexive & symmetric both = 2^(n(n−1)/2)."],
      ]},
      { name: "Functions", leaves: [
        ["Domain & range", 0.6, 3,
          "Domain of rational, root, log, inverse-trig combos; range by y=f(x) → x in terms of y, by completing square, by min/max.",
          "Range of very complicated composite functions via calculus proofs.",
          "Range of a·sinx + b·cosx = [−√(a²+b²), √(a²+b²)]."],
        ["One-one, onto, bijection & counting functions", 0.4, 2,
          "Tests (horizontal line, derivative sign), number of functions mⁿ, one-one ⁿPₘ, onto using inclusion–exclusion (small n).",
          "Stirling numbers theory.",
          "Onto from 4 to 2 elements: 2⁴−2 = 14."],
        ["Composition & inverse of functions", 0.3, 2,
          "fog, gof, domain of composition, finding inverse, f(f⁻¹(x))=x.",
          "Inverse of piecewise functions with many pieces.", ""],
        ["Even/odd, periodic & standard graphs (|x|, [x], {x})", 0.2, 2,
          "Even/odd tests, period of sin/cos/tan combinations (LCM rule), graphs of mod, greatest integer, fractional part.",
          "Period proofs for non-standard functions.",
          "Period of |sin x| = π, sin⁴x+cos⁴x = π/2."],
      ]},
    ],
  },
  {
    id: "M02", subject: "M", name: "Algebra Basics: Indices, Logarithms, Equations & Quadratics",
    ncert: "NCERT 10 Ch 4 (Quadratic Eq), 11 Ch 4 (Quadratic part), 11 Ch 5 (Inequalities); Logs: not in NCERT",
    obj: "RD Sharma Objective: Quadratic Equations & Expressions; Logarithms (use RD Sharma Class 11 for logs if needed)",
    prereq: ["Algebraic identities (a±b)², (a±b)³, a³±b³", "Factorisation by splitting middle term", "Log values: log2=0.3010, log3=0.4771, log5=0.6990, log7=0.8451"],
    speed: [
      "Quadratic me pehle discriminant ka sign socho — aadhe questions wahi se solve.",
      "Options se value daal ke check (back-substitution) — equations wale MCQs me sabse fast.",
      "Log: sab kuch ek base me convert karo, log_a b · log_b a = 1 yaad rakho.",
    ],
    topics: [
      { name: "Indices & Surds", leaves: [
        ["Laws of indices & exponential equations", 0.3, 1,
          "aᵐ·aⁿ, (aᵐ)ⁿ, a⁰, negative/fractional powers, same-base equations.",
          "Irrational exponent theory.", "Base same karo, powers equate karo."],
        ["Surds & rationalisation", 0.2, 1,
          "Rationalise a+√b, √(a+2√b) = √x+√y trick, comparing surds.",
          "Nested surds of 3+ levels.", "√(a+2√b): do numbers dhundho jinka sum a, product b."],
      ]},
      { name: "Logarithms", leaves: [
        ["Log properties & change of base", 0.6, 2,
          "Product/quotient/power rules, change of base, a^(log_a x)=x, log_a b·log_b c = log_a c, number of digits via log.",
          "Log tables usage, natural log series.",
          "Digits in 2^100 = ⌊100·0.3010⌋+1 = 31."],
        ["Log equations & inequalities", 0.4, 2,
          "Solve with domain check (argument > 0, base > 0, ≠1), inequality direction flips when base < 1.",
          "Transcendental equations needing graphs of many curves.",
          "Answer nikalne ke baad domain check MUST — trap yahi hota hai."],
        ["Characteristic & mantissa", 0.1, 1,
          "Meaning of characteristic, number of digits / zeros after decimal.",
          "Anti-log table reading.", ""],
      ]},
      { name: "Expansions, Factorisation & Linear Equations", leaves: [
        ["Algebraic identities & expansions", 0.3, 1,
          "All standard identities, a³+b³+c³−3abc, if a+b+c=0 then a³+b³+c³=3abc, x+1/x type manipulations.",
          "Symmetric polynomial theory.", "x+1/x = k ⇒ x²+1/x² = k²−2, x³+1/x³ = k³−3k."],
        ["Remainder & factor theorem, polynomial division", 0.2, 1,
          "Remainder = f(a), factor if f(a)=0, finding unknown coefficients.",
          "Polynomial long division of degree 5+.", ""],
        ["Simultaneous linear equations (2–3 variables)", 0.4, 1,
          "Elimination/substitution, conditions for unique/infinite/no solution (a1/a2 vs b1/b2 vs c1/c2).",
          "Gaussian elimination theory (matrix method covered in Matrices).",
          "Ratio test: a1/a2 ≠ b1/b2 → unique."],
      ]},
      { name: "Quadratic Equations & Inequalities", leaves: [
        ["Nature of roots (discriminant)", 0.6, 2,
          "D>0, =0, <0; rational roots when D perfect square; conditions for real/equal/imaginary roots with parameters.",
          "Cubic discriminant.", "Coefficients rational + D perfect square ⇒ rational roots."],
        ["Sum/product of roots & symmetric functions", 0.6, 3,
          "α+β, αβ, α²+β², α³+β³, α−β, 1/α+1/β, αⁿ+βⁿ recurrence; cubic: Σα, Σαβ, αβγ.",
          "Newton's identities for degree > 3.",
          "α²+β² = (α+β)² − 2αβ; |α−β| = √D/|a|."],
        ["Forming equations & transformed roots", 0.3, 2,
          "x² − Sx + P = 0; roots 1/α, α+k, kα, α² → substitute x→1/x, x→x−k, x→x/k.",
          "General Tschirnhaus transformations.", "Roots reciprocal ⇒ coefficients reverse kar do."],
        ["Common roots", 0.2, 2,
          "One common root condition (cross-multiplication), both roots common ⇒ ratios equal.",
          "Common roots of cubic + quadratic.", ""],
        ["Location of roots & sign of quadratic", 0.3, 3,
          "Both roots > k, < k, k between roots (a·f(k) < 0), ax²+bx+c > 0 ∀x ⇔ a>0, D<0; min/max value −D/4a.",
          "Roots in interval with 3+ conditions for higher degree.",
          "k beech me ⇒ sirf a·f(k) < 0 check karo."],
        ["Linear, quadratic & modulus inequalities", 0.4, 2,
          "Wavy curve (sign scheme) method, |x−a| < b, |x−a| > b, rational inequalities.",
          "Inequalities with 3+ modulus terms nested.",
          "Wavy curve: critical points line pe, rightmost + se start, even power pe sign same."],
      ]},
    ],
  },
  {
    id: "M03", subject: "M", name: "Sequences & Series",
    ncert: "NCERT 10 Ch 5 (AP), 11 Ch 8 (Sequences & Series)",
    obj: "RD Sharma Objective: Arithmetic Progressions; Geometric Progressions; Harmonic Progressions; Special Series",
    prereq: ["Sum formulas Σn, Σn², Σn³", "Basic algebra manipulation"],
    speed: [
      "3 terms AP me: a−d, a, a+d lo; GP me: a/r, a, ar — calculation aadha.",
      "Options check: n=1, n=2 daal ke Sₙ ki formula verify karo — 30 sec me answer.",
      "AM ≥ GM ≥ HM wale min/max questions: equality condition se value turant.",
    ],
    topics: [
      { name: "Arithmetic Progression", leaves: [
        ["AP: nth term & sum", 0.6, 2,
          "aₙ, Sₙ, aₙ = Sₙ − Sₙ₋₁, nth term from end, sum of numbers divisible by k in a range.",
          "Proofs of formulas.", "Sₙ = n/2 (first + last). Middle term × n = sum (odd n)."],
        ["AP properties & arithmetic means", 0.3, 2,
          "Terms equidistant from ends, inserting n AMs, if a,b,c in AP ⇒ 2b=a+c, operations on AP.",
          "", "n AMs between a and b: sum = n·(a+b)/2."],
      ]},
      { name: "Geometric Progression", leaves: [
        ["GP: nth term, sum & infinite GP", 0.7, 2,
          "aₙ, Sₙ, S∞ = a/(1−r) for |r|<1, GMs insertion, recurring decimals to fraction, product of n terms.",
          "Convergence tests theory.", "0.3̄ type → infinite GP. Product of n GMs = (ab)^(n/2)."],
      ]},
      { name: "HP & Means", leaves: [
        ["Harmonic progression", 0.3, 2,
          "Reciprocals form AP, nth term of HP, HM of two numbers.",
          "Sum of HP (no closed form — never asked).", "HP ka sum ka formula nahi hota — trap."],
        ["AM–GM–HM inequality & min/max", 0.5, 3,
          "A ≥ G ≥ H, G² = A·H for two numbers, min of a/b + b/a type, min of sum given product constant.",
          "Weighted power mean inequality, Cauchy–Schwarz deep use.",
          "Product fixed ⇒ sum minimum when all equal."],
      ]},
      { name: "Special Series", leaves: [
        ["Σn, Σn², Σn³ based series", 0.4, 2,
          "Sum of series whose nth term is polynomial in n; 1²+3²+5²…, 1·2+2·3+… .",
          "Bernoulli numbers.", "Tₙ nikalo, fir Σ lagao."],
        ["Arithmetico-geometric series (AGP)", 0.3, 2,
          "Sₙ and S∞ using S − rS method.",
          "", "S∞ of AGP = a/(1−r) + dr/(1−r)²."],
        ["Method of differences & telescoping", 0.4, 3,
          "Differences in AP/GP ⇒ find Tₙ; 1/(n(n+1)) type telescoping; partial fractions in series.",
          "Higher order difference tables beyond 2nd order.",
          "1/(n(n+1)) = 1/n − 1/(n+1) — cancel ho jata hai."],
      ]},
    ],
  },
  {
    id: "M04", subject: "M", name: "Permutations, Combinations & Binomial Theorem",
    ncert: "NCERT 11 Ch 6 (P&C), 11 Ch 7 (Binomial Theorem)",
    obj: "RD Sharma Objective: Permutations & Combinations; Binomial Theorem",
    prereq: ["Factorials till 10! yaad (10! = 3628800)", "ⁿCᵣ = ⁿCₙ₋ᵣ, Pascal rule", "Powers of 2 till 2¹⁰"],
    speed: [
      "Pehle decide: ORDER matter karta hai? Haan → P, Nahi → C. Ye 1 question 50% galtiyaan rokta hai.",
      "Together wale → group ko 1 object; Not together → Total − together.",
      "Binomial general term Tᵣ₊₁ = ⁿCᵣ aⁿ⁻ʳ bʳ — power equation likho, r nikalo.",
    ],
    topics: [
      { name: "Counting Principle & Permutations", leaves: [
        ["Fundamental principle of counting", 0.3, 1,
          "Multiplication vs addition rule, number formation (digits with/without repetition, divisibility).",
          "", "Pehle restricted place bharo (e.g. last digit for even)."],
        ["Permutations: repetition & identical objects", 0.6, 3,
          "ⁿPᵣ, n!/(p!q!r!), arrangements with restrictions (together, not together, vowels at even places).",
          "Permutations of multisets with complex restrictions via generating functions.",
          "Not together (vowels) → gap method: consonants arrange, gaps me vowels."],
        ["Circular permutations", 0.3, 2,
          "(n−1)!, necklace/garland (n−1)!/2, round table with restrictions.",
          "Burnside's lemma.", "Necklace/garland me clockwise = anticlockwise ⇒ ÷2."],
        ["Rank of a word in dictionary", 0.2, 2,
          "Count words before the given word letter by letter, with repeated letters.",
          "", "Alphabetical order me har position ke liye 'kitne letters chhote hain' × remaining!"],
      ]},
      { name: "Combinations", leaves: [
        ["Selections with restrictions", 0.5, 3,
          "ⁿCᵣ properties, at least/at most, selection from identical objects, total selections 2ⁿ−1, committee problems.",
          "Combinatorial proofs of identities.", "'At least 1' = Total − none."],
        ["Geometry counting (lines, triangles, diagonals)", 0.3, 2,
          "Lines ⁿC₂, triangles ⁿC₃ (minus collinear), diagonals n(n−3)/2, parallelograms from parallel lines ᵐC₂·ⁿC₂.",
          "", "Diagonals = ⁿC₂ − n."],
        ["Distribution & division into groups", 0.3, 3,
          "Identical objects into groups (stars & bars ⁿ⁺ʳ⁻¹Cᵣ₋₁), distinct into groups, equal groups ÷ k!.",
          "Distinct objects into identical boxes (Stirling).",
          "x₁+x₂+…+x_r = n (xi ≥ 0): ⁿ⁺ʳ⁻¹C_{r−1}."],
        ["Derangements (basic)", 0.1, 2,
          "D₁=0, D₂=1, D₃=2, D₄=9, D₅=44; wrong envelope problems.",
          "General derangement proofs.", "D₄ = 9, D₅ = 44 ratta maar lo."],
      ]},
      { name: "Binomial Theorem", leaves: [
        ["General term & middle term", 0.6, 2,
          "Tᵣ₊₁, middle term(s) for even/odd n, rth term from end, number of terms n+1.",
          "Multinomial beyond trinomial counting.", ""],
        ["Coefficient of xᵏ & term independent of x", 0.4, 3,
          "Set power of x = k in general term; product of two expansions; greatest coefficient.",
          "Greatest term with non-integer expressions deep.",
          "(x + 1/x)ⁿ type: power = n − 2r."],
        ["Sum of coefficients & binomial identities", 0.3, 2,
          "Put x=1, x=−1; ΣⁿCᵣ = 2ⁿ, sum of odd/even coefficients = 2ⁿ⁻¹, Σr·ⁿCᵣ = n·2ⁿ⁻¹.",
          "Calculus-based identities beyond first derivative.", "x=1 daalo ⇒ sum of coefficients."],
        ["Remainder / divisibility using binomial", 0.1, 2,
          "Write base as (k±1)ⁿ and expand; last digits.",
          "", "7¹⁰⁰ mod 48: 7² = 49 = 48+1 ⇒ remainder 1."],
      ]},
    ],
  },
  {
    id: "M05", subject: "M", name: "Probability",
    ncert: "NCERT 11 Ch 14, 12 Ch 13 (Probability)",
    obj: "RD Sharma Objective: Probability",
    prereq: ["P&C chapter complete (MUST)", "Fractions fast simplification", "Cards (52), dice (36 outcomes), coins (2ⁿ) sample spaces yaad"],
    speed: [
      "Complement use karo: P(at least one) = 1 − P(none).",
      "Bayes: tree diagram banao, 3 branches max — formula ratta ki zaroorat nahi.",
      "2 dice sum table (sum 7 = 6 ways, 6/8 = 5 ways…) yaad rakho.",
    ],
    topics: [
      { name: "Basic Probability", leaves: [
        ["Sample space & classical probability", 0.8, 2,
          "Coins, dice, cards, balls-in-bag, arrangement-based probability using P&C.",
          "Axiomatic σ-algebra theory.", "Favourable/Total — dono ko same type (ordered/unordered) me count karo."],
        ["Addition rule, complement & mutually exclusive events", 0.5, 2,
          "P(A∪B), P(A∪B∪C), P(A'), P(A∩B'), odds in favour/against.",
          "", "Odds a:b ⇒ P = a/(a+b)."],
      ]},
      { name: "Conditional Probability", leaves: [
        ["Conditional probability & multiplication rule", 0.6, 3,
          "P(A|B) = P(A∩B)/P(B), successive draws without replacement, reduced sample space trick.",
          "Measure-theoretic conditioning.", "Reduced sample space: given B ⇒ total = n(B)."],
        ["Independent events", 0.5, 2,
          "P(A∩B)=P(A)P(B), independent vs mutually exclusive difference, problems like 'target hit by at least one'.",
          "Pairwise vs mutual independence proofs.", ""],
        ["Total probability & Bayes' theorem", 0.6, 3,
          "Partition, total probability, Bayes for 2–3 urns/machines/diagnostic test problems.",
          "Continuous Bayes.", "Bayes = (is branch ka product)/(sab branches ka sum)."],
      ]},
      { name: "Random Variables & Distributions", leaves: [
        ["Random variable, probability distribution, mean & variance", 0.3, 2,
          "Discrete distribution table, ΣP=1, E(X), Var(X)=E(X²)−(E(X))².",
          "Continuous distributions, pdf integration.", ""],
        ["Binomial distribution", 0.5, 2,
          "P(X=r) = ⁿCᵣ pʳ qⁿ⁻ʳ, mean np, variance npq, at least/at most, find n,p from mean & variance.",
          "Poisson/normal approximations.", "Mean/variance diya ⇒ q = var/mean."],
        ["Geometric & miscellaneous probability", 0.2, 2,
          "Probability with lengths/areas (simple), games where players toss alternately (infinite GP).",
          "", "A first toss wins: p/(1−q²) type — infinite GP."],
      ]},
    ],
  },
  {
    id: "M06", subject: "M", name: "Matrices & Determinants",
    ncert: "NCERT 12 Ch 3 (Matrices), 12 Ch 4 (Determinants)",
    obj: "RD Sharma Objective: Matrices; Determinants; Adjoint & Inverse; Simultaneous Linear Equations",
    prereq: ["2×2 and 3×3 determinant expansion fast", "Linear equations (M02)"],
    speed: [
      "Property-based questions: kabhi expand mat karo pehle — row/column operations se zeros banao.",
      "Formulas ka card: |kA| = kⁿ|A|, |adj A| = |A|ⁿ⁻¹, adj(adj A) = |A|ⁿ⁻²A, |A⁻¹| = 1/|A|.",
      "Options check with simple matrices (I, diagonal) — 'which is always true' type me.",
    ],
    topics: [
      { name: "Matrices", leaves: [
        ["Types of matrices & operations", 0.6, 2,
          "Order, types (diagonal, scalar, identity, triangular), addition, multiplication (non-commutative), Aⁿ patterns.",
          "Block matrices, matrix calculus.", "Aⁿ pattern: A², A³ nikal ke pattern dekho."],
        ["Transpose, symmetric & skew-symmetric", 0.4, 2,
          "(AB)ᵀ = BᵀAᵀ, every matrix = symmetric + skew; diagonal of skew = 0; number of symmetric matrices with entries.",
          "", "Skew-symmetric odd order ⇒ |A| = 0."],
        ["Special matrices (orthogonal, idempotent, nilpotent, involutory)", 0.4, 2,
          "Definitions + determinant/inverse consequences, trace properties.",
          "Eigenvalue theory deep (only basics if asked).", "Orthogonal ⇒ |A| = ±1, A⁻¹ = Aᵀ."],
        ["Rank of a matrix (basic)", 0.3, 2,
          "Echelon form for 3×3/3×4, rank and consistency link.",
          "Rank–nullity theorem proofs.", ""],
      ]},
      { name: "Determinants", leaves: [
        ["Evaluation & properties of determinants", 0.9, 3,
          "All properties (row swap, common factor, R₁→R₁+kR₂, zero rows), factor theorem in determinants, determinant equations.",
          "4×4 determinants by hand.", "Sab rows add karo — common factor aksar nikal aata hai."],
        ["Minors, cofactors & area of triangle", 0.4, 1,
          "Minor/cofactor definitions, expansion using cofactors, area = ½|det|, collinearity condition.",
          "", "Collinear ⇔ area determinant = 0."],
      ]},
      { name: "Adjoint, Inverse & Linear Systems", leaves: [
        ["Adjoint & its properties", 0.8, 3,
          "adj A, A·adj A = |A|I, |adj A| = |A|ⁿ⁻¹, adj(adj A), adj(AB) = adj B·adj A.",
          "Proofs of these properties.", "Ek formula card roz dekho — isi se 1–2 Q har saal."],
        ["Inverse of a matrix", 0.4, 2,
          "A⁻¹ = adj A/|A|, (AB)⁻¹ = B⁻¹A⁻¹, inverse using A² + kA + I = 0 type relations.",
          "Gauss–Jordan inverse of 4×4.", "A² − 5A + 7I = 0 ⇒ A⁻¹ = (5I − A)/7."],
        ["System of linear equations (Cramer / consistency)", 0.7, 3,
          "Unique (|A|≠0), infinite/no solution (|A|=0 and (adj A)B = 0 or ≠ 0), homogeneous systems non-trivial solution condition.",
          "LU decomposition.", "Homogeneous non-trivial ⇔ |A| = 0."],
      ]},
    ],
  },
  {
    id: "M07", subject: "M", name: "Trigonometry",
    ncert: "NCERT 10 Ch 8–9, 11 Ch 3 (Trig Functions), 12 Ch 2 (Inverse Trig); Properties of triangles: not in NCERT",
    obj: "RD Sharma Objective: Trigonometric Ratios & Identities; Trigonometric Equations; Inverse Trigonometric Functions; Properties of Triangles; Heights & Distances",
    prereq: ["Trig table 0°, 30°, 45°, 60°, 90° + ASTC rule", "Allied angles (90°±θ, 180°±θ)", "Values: sin15°, cos15°, sin18°, cos36°, tan22.5°"],
    speed: [
      "Identity questions: θ = 0, 30°, 45° daal ke options check — sabse fast.",
      "Max/min of a sinθ + b cosθ + c = c ± √(a²+b²).",
      "Inverse trig: principal value ranges ka ek card bana lo aur roz 1 min dekho.",
    ],
    topics: [
      { name: "Ratios & Identities", leaves: [
        ["Trig ratios, radian measure & allied angles", 0.3, 1,
          "Degree ↔ radian, arc length l = rθ, signs in quadrants, allied angle reduction.",
          "", "l = rθ me θ radian me hona chahiye."],
        ["Compound angle identities", 0.8, 2,
          "sin(A±B), cos(A±B), tan(A±B), cos(A+B)cos(A−B) = cos²A − sin²B, tan(A+B+C) conditions.",
          "Identities for 4+ angles.", "A+B = 45° ⇒ (1+tanA)(1+tanB) = 2."],
        ["Multiple & sub-multiple angles", 0.5, 2,
          "sin2A, cos2A (3 forms), tan2A, sin3A, cos3A, half-angle formulas.",
          "", "cosA·cos2A·cos4A…cos2ⁿ⁻¹A = sin2ⁿA/(2ⁿ sinA)."],
        ["Sum–product transformations", 0.3, 2,
          "sinC ± sinD, cosC ± cosD, 2sinAcosB forms; series like cos20·cos40·cos80.",
          "", "cos20°·cos40°·cos80° = 1/8."],
        ["Maximum & minimum of trig expressions", 0.4, 3,
          "a sinθ + b cosθ, sin²/cos² combos, AM–GM with tan/cot, range of expressions.",
          "Calculus-heavy trig optimisation.", "a sin²θ + b cosec²θ min = 2√(ab) (if condition holds) — check equality."],
      ]},
      { name: "Trigonometric Equations", leaves: [
        ["General solutions of trig equations", 0.6, 2,
          "sinθ = sinα ⇒ θ = nπ + (−1)ⁿα; cos ⇒ 2nπ ± α; tan ⇒ nπ + α; a cosθ + b sinθ = c; number of solutions in interval.",
          "Transcendental trig equations.", "Interval me solutions count ke liye graph sketch karo."],
      ]},
      { name: "Inverse Trigonometric Functions", leaves: [
        ["Domain, range & principal values", 0.3, 2,
          "Principal value branches of all six, sin⁻¹(sin x) for x outside range.",
          "", "sin⁻¹(sin x): x ko [−π/2, π/2] me laao."],
        ["Inverse trig identities & equations", 0.4, 3,
          "tan⁻¹x + tan⁻¹y, sin⁻¹x + cos⁻¹x = π/2, 2tan⁻¹x forms, simplification by substitution (x = tanθ).",
          "Series of inverse trig with telescoping of 20+ terms (basic telescoping ok).",
          "√(1−x²) dikhe ⇒ x = sinθ ya cosθ substitute."],
      ]},
      { name: "Properties & Solutions of Triangles", leaves: [
        ["Sine rule, cosine rule & projection formula", 0.5, 2,
          "a/sinA = 2R, cosine rule, projection a = b cosC + c cosB, finding angles.",
          "Napier's analogy deep use.", "Sides ratio diya ⇒ cosine rule se angle."],
        ["Half-angle formulas, area, R and r", 0.3, 2,
          "Δ = ½ab sinC = √(s(s−a)(s−b)(s−c)), R = abc/4Δ, r = Δ/s, half-angle in terms of s.",
          "Escribed circles, m-n theorem deep.", ""],
        ["Heights & distances", 0.4, 1,
          "Angles of elevation/depression, two-observer problems, tower/pole/shadow problems.",
          "3D heights & distances with multiple planes.", "tan30 = 1/√3, tan60 = √3 — ratio se direct answer."],
      ]},
    ],
  },
  {
    id: "M08", subject: "M", name: "Coordinate Geometry",
    ncert: "NCERT 10 Ch 7, 11 Ch 9 (Straight Lines), 11 Ch 10 (Conic Sections); Pair of lines: not in NCERT",
    obj: "RD Sharma Objective: Cartesian Coordinates; Straight Lines; Pair of Straight Lines; Circle; Parabola; Ellipse; Hyperbola",
    prereq: ["Distance & section formula", "Slope basics, tanθ values", "Completing the square (for circle/conic centre)"],
    speed: [
      "Rough diagram HAMESHA — 60% options diagram se eliminate ho jaate hain.",
      "Conic comparison table (a, b, e, foci, directrix, LR) ek page pe — roz 1 baar dekho.",
      "Parametric points (at², 2at), (a cosθ, b sinθ) use karo — algebra kam.",
    ],
    topics: [
      { name: "Basics & Locus", leaves: [
        ["Distance, section formula, centroid, incentre, area", 0.6, 2,
          "Internal/external division, centroid, incentre, circumcentre (right triangle shortcut), area of triangle/quadrilateral.",
          "Orthocentre derivations for general triangle (know only right-triangle shortcut).",
          "Right triangle: circumcentre = hypotenuse ka midpoint."],
        ["Locus", 0.3, 2,
          "Let point (h,k), write condition, replace h→x, k→y.",
          "", ""],
      ]},
      { name: "Straight Lines", leaves: [
        ["Forms of equation of a line", 0.6, 2,
          "Slope-point, two-point, intercept, normal form, general form conversions.",
          "", "Intercept form: x/a + y/b = 1 — area of triangle with axes = ½|ab|."],
        ["Angle between lines, parallel & perpendicular", 0.4, 2,
          "tanθ = |(m₁−m₂)/(1+m₁m₂)|, parallel/perpendicular line through a point.",
          "", "ax+by+c=0 ke perpendicular: bx−ay+k=0."],
        ["Distance from point to line & between parallel lines", 0.4, 2,
          "|ax₁+by₁+c|/√(a²+b²), |c₁−c₂|/√(a²+b²), foot of perpendicular, image of point.",
          "", "Image formula: (x−x₁)/a = (y−y₁)/b = −2(ax₁+by₁+c)/(a²+b²)."],
        ["Family of lines & concurrency", 0.2, 2,
          "L₁ + λL₂ = 0, condition of concurrency (determinant = 0), angle bisectors.",
          "", ""],
      ]},
      { name: "Pair of Straight Lines", leaves: [
        ["Homogeneous equation & angle between pair of lines", 0.4, 2,
          "ax²+2hxy+by²=0: m₁+m₂ = −2h/b, m₁m₂ = a/b, tanθ = 2√(h²−ab)/|a+b|, perpendicular if a+b=0, condition for pair (Δ=0).",
          "Homogenisation of curve with line (chord of contact to origin) deep.", "Perpendicular ⇔ a + b = 0."],
      ]},
      { name: "Circle", leaves: [
        ["Standard & general equation of circle", 0.6, 2,
          "Centre (−g,−f), r = √(g²+f²−c), diameter form, circle through 3 points, intercepts on axes.",
          "", "Diameter form: (x−x₁)(x−x₂)+(y−y₁)(y−y₂)=0."],
        ["Tangent & normal to circle", 0.4, 3,
          "Tangent at point (T=0), condition of tangency c² = a²(1+m²), length of tangent √S₁, normal passes through centre.",
          "Director circle of general conics.", "Length of tangent = √S₁."],
        ["Position, chords & orthogonal circles", 0.3, 2,
          "Point inside/outside, chord with given midpoint (T=S₁), two circles relative position, orthogonality 2g₁g₂+2f₁f₂ = c₁+c₂.",
          "Radical centre deep problems, coaxal systems.", ""],
      ]},
      { name: "Conic Sections", leaves: [
        ["Parabola: standard forms, focus, directrix, latus rectum", 0.6, 2,
          "4 standard forms, vertex shifted parabola, LR = 4a, focal distance = x + a.",
          "", "Focal chord ends t₁t₂ = −1."],
        ["Parabola: tangent, normal & parametric form", 0.3, 3,
          "Tangent y = mx + a/m, parametric (at², 2at), normal at t.",
          "Co-normal points deep, chord of contact advanced.", ""],
        ["Ellipse: standard form, eccentricity, foci, LR", 0.6, 2,
          "b² = a²(1−e²), foci (±ae,0), directrix x = ±a/e, LR = 2b²/a, sum of focal distances = 2a.",
          "", "Sum of focal distances = 2a (major axis)."],
        ["Ellipse: tangent & auxiliary circle", 0.2, 2,
          "Tangent y = mx ± √(a²m²+b²), parametric (a cosθ, b sinθ).",
          "Conjugate diameters.", ""],
        ["Hyperbola: standard form, e, asymptotes, rectangular hyperbola", 0.6, 2,
          "b² = a²(e²−1), asymptotes y = ±(b/a)x, conjugate hyperbola e relation 1/e₁² + 1/e₂² = 1, xy = c².",
          "", "Rectangular hyperbola e = √2."],
        ["Hyperbola: tangent", 0.1, 2,
          "Condition c² = a²m² − b², tangent at point.",
          "", ""],
      ]},
    ],
  },
  {
    id: "M09", subject: "M", name: "Calculus",
    ncert: "NCERT 11 Ch 12, 12 Ch 5–9 (Continuity, AOD, Integrals, Area, Diff. Eq.)",
    obj: "RD Sharma Objective: Limits; Continuity & Differentiability; Differentiation; Tangents & Normals; Monotonicity; Maxima & Minima; Indefinite Integrals; Definite Integrals; Area; Differential Equations",
    prereq: ["Functions & graphs (M01)", "Trig identities (M07)", "Standard derivative & integral tables yaad", "Straight lines (M08)"],
    speed: [
      "Standard limits card: sinx/x, (eˣ−1)/x, (aˣ−1)/x, ln(1+x)/x, (1+x)^(1/x) → e.",
      "1^∞ form: e^(lim (f−1)·g) — 1 line me answer.",
      "Definite integral: pehle KING's property (a+b−x) try karo — 50% questions 1 step me.",
      "Options se differentiate karke check karna (indefinite integral me) — 20 sec.",
    ],
    topics: [
      { name: "Limits", leaves: [
        ["Standard limits & algebraic limits", 0.7, 2,
          "Factorisation, rationalisation, standard limits, limits at infinity (highest power), LHL/RHL with |x| and [x].",
          "ε-δ definition proofs.", "x→∞: highest power ka coefficient ratio."],
        ["L'Hospital's rule & series expansions", 0.4, 2,
          "0/0, ∞/∞ forms, expansions of sinx, cosx, eˣ, ln(1+x) up to 3 terms.",
          "Taylor series with remainder.", "sinx ≈ x − x³/6: x³ wale limits instant."],
        ["Indeterminate 1^∞, 0^0 forms", 0.3, 2,
          "lim f^g = e^(lim g(f−1)) when f→1, g→∞.",
          "", ""],
      ]},
      { name: "Continuity & Differentiability", leaves: [
        ["Continuity & differentiability", 0.6, 3,
          "LHL=RHL=f(a), find k for continuity, LHD vs RHD, points of non-differentiability of |f(x)|, [x], max/min functions.",
          "Uniform continuity, pathological functions.", "|x−a| ka corner = non-differentiable point; count graph se."],
      ]},
      { name: "Differentiation", leaves: [
        ["Rules: chain, implicit, parametric & logarithmic differentiation", 0.7, 2,
          "Product/quotient/chain, implicit dy/dx, parametric dy/dx, xˣ type via log, derivative of inverse trig by substitution.",
          "nth derivative of general functions (Leibniz deep).", "Implicit: dy/dx = −f_x/f_y."],
        ["Higher order derivatives", 0.2, 1,
          "Second derivative, d²y/dx² of parametric, simple relations like y'' + y = 0.",
          "", ""],
      ]},
      { name: "Applications of Derivatives", leaves: [
        ["Tangents & normals", 0.5, 2,
          "Slope = dy/dx, equations of tangent/normal, angle between curves, tangent parallel/perpendicular to axis.",
          "Subtangent/subnormal deep.", ""],
        ["Increasing / decreasing functions", 0.3, 2,
          "Sign of f'(x) intervals, monotonic for all x (f' ≥ 0 ⇒ D ≤ 0 type conditions).",
          "", ""],
        ["Maxima & minima", 0.7, 3,
          "First & second derivative tests, global max/min in closed interval, word problems (area/volume/distance).",
          "Lagrange multipliers.", "Closed interval: critical points + end points dono check."],
        ["Rate of change, Rolle's & Mean Value Theorem", 0.2, 1,
          "dA/dt type chain rule, Rolle's/LMVT conditions and finding c.",
          "Proofs of theorems.", ""],
      ]},
      { name: "Integration", leaves: [
        ["Indefinite integrals: standard forms & substitution", 0.6, 2,
          "Standard integrals table, substitution, ∫dx/(x²±a²), ∫dx/√(a²−x²), trig integrals using identities.",
          "Reduction formulas deep.", "∫f'(x)/f(x) dx = ln|f(x)| — numerator me derivative dhundo."],
        ["Integration by parts", 0.4, 2,
          "ILATE, ∫eˣ(f + f')dx = eˣf, ∫eᵃˣ sin bx type.",
          "", "eˣ(f + f') pattern dikhe ⇒ answer eˣf."],
        ["Partial fractions", 0.3, 2,
          "Linear and repeated linear factors, quadratic factor basic.",
          "Very high degree denominators.", "Cover-up method for linear factors."],
        ["Definite integrals & properties", 0.8, 3,
          "Fundamental theorem, King's (a+b−x), even/odd over [−a,a], periodic, ∫₀²ᵃ property, modulus & [x] integrals, Leibniz rule (basic).",
          "Limit of sum as definite integral (basic only), improper integrals.",
          "∫₀^(π/2) sinⁿx/(sinⁿx+cosⁿx) dx = π/4."],
        ["Area under curves", 0.5, 2,
          "Area between curve and axis, between two curves (parabola–line, circle), area using symmetry.",
          "Area in polar coordinates.", "Sketch + intersection points pehle; standard: y² = 4ax & x² = 4ay area = 16a²/3."],
      ]},
      { name: "Differential Equations", leaves: [
        ["Order, degree & variable separable", 0.3, 2,
          "Order/degree (polynomial in derivatives), formation by eliminating constants, variable separable, linear first order (IF).",
          "Exact equations, higher order linear ODEs.", "Degree tab hi define jab derivatives polynomial me hon."],
      ]},
    ],
  },
  {
    id: "M10", subject: "M", name: "Vectors & 3D Geometry",
    ncert: "NCERT 12 Ch 10 (Vector Algebra), 11 Ch 11 + 12 Ch 11 (3D Geometry)",
    obj: "RD Sharma Objective: Vectors; Scalar Product; Vector Product; Scalar Triple Product; Direction Cosines; Straight Line in Space; The Plane",
    prereq: ["Coordinate geometry basics", "3×3 determinants (M06)", "Trig values"],
    speed: [
      "Dot = cos wala, Cross = sin wala — angle/area questions turant pehchaano.",
      "Coplanar ⇔ [a b c] = 0 — determinant se 30 sec.",
      "Projection of a on b = (a·b)/|b|.",
    ],
    topics: [
      { name: "Vector Algebra", leaves: [
        ["Vector basics, position vector & section formula", 0.4, 1,
          "Addition, unit vector, collinearity, section formula, direction cosines of vector.",
          "", ""],
        ["Scalar (dot) product & projection", 0.8, 2,
          "a·b = |a||b|cosθ, angle, perpendicular condition, projection, |a+b|² expansions.",
          "", "|a+b| = |a−b| ⇒ a ⊥ b."],
        ["Vector (cross) product & area", 0.7, 2,
          "a×b, |a×b| = area of parallelogram, triangle area ½|AB×AC|, unit vector ⊥ to both.",
          "", "Area of triangle = ½|AB × AC|."],
        ["Scalar triple product, volume & coplanarity", 0.6, 2,
          "[a b c] as determinant, volume of parallelepiped/tetrahedron (1/6), coplanarity.",
          "", "Tetrahedron volume = (1/6)|[a b c]|."],
        ["Vector triple product", 0.2, 2,
          "a×(b×c) = (a·c)b − (a·b)c.",
          "Reciprocal vectors.", "BAC–CAB rule."],
        ["Applications in mechanics (work, moment)", 0.3, 1,
          "Work = F·d, moment/torque = r×F.",
          "", ""],
      ]},
      { name: "3D Geometry", leaves: [
        ["Direction cosines & ratios", 0.5, 2,
          "l²+m²+n² = 1, DRs from two points, angle between lines, projection of segment.",
          "", ""],
        ["Line in 3D", 0.4, 2,
          "Vector & Cartesian form, angle between lines, shortest distance between skew lines, point on line.",
          "Line-plane family advanced.", "SD = |(b−a)·(d₁×d₂)|/|d₁×d₂|."],
        ["Plane", 0.4, 2,
          "Normal form, intercept form, plane through 3 points, distance of point from plane, angle between planes.",
          "", "Distance formula same as 2D line wala structure."],
        ["Angle & distance between line and plane", 0.2, 2,
          "sinθ = |n·b|/(|n||b|), line parallel/lying in plane conditions.",
          "", ""],
      ]},
    ],
  },
  {
    id: "M11", subject: "M", name: "Statistics",
    ncert: "NCERT 11 Ch 13 (Statistics), Class 10 Ch 13–14 (mean/median/mode of grouped data)",
    obj: "RD Sharma Objective: Measures of Central Tendency; Measures of Dispersion",
    prereq: ["Fast arithmetic & fractions", "Σ notation"],
    speed: [
      "Change of origin → mean shifts, SD same. Change of scale ×k → mean ×k, SD ×|k|.",
      "Variance = mean of squares − square of mean — sabse fast formula.",
    ],
    topics: [
      { name: "Central Tendency", leaves: [
        ["Mean (arithmetic, weighted, combined)", 0.5, 2,
          "Individual, discrete, grouped (step deviation), combined mean, correcting wrong observation.",
          "Geometric/harmonic mean of grouped data deep.", "Wrong observation fix: new sum = old sum − wrong + right."],
        ["Median & mode", 0.4, 1,
          "Ungrouped and grouped formulas, empirical relation Mode = 3 Median − 2 Mean.",
          "Ogive drawing by hand.", ""],
        ["Frequency distributions", 0.1, 1,
          "Class marks, cumulative frequency, reading tables.",
          "", ""],
      ]},
      { name: "Dispersion", leaves: [
        ["Mean deviation", 0.2, 1,
          "About mean and median for simple data.",
          "", ""],
        ["Variance & standard deviation (incl. origin/scale change)", 0.6, 3,
          "σ² = Σx²/n − x̄², combined variance of two groups, effect of adding/multiplying constants, correcting wrong observation.",
          "Moments, skewness, kurtosis.", "Variance of first n natural numbers = (n²−1)/12."],
        ["Coefficient of variation", 0.2, 1,
          "CV = σ/x̄ × 100, comparing consistency.",
          "", "Lower CV = more consistent."],
      ]},
    ],
  },
  {
    id: "M12", subject: "M", name: "Complex Numbers",
    ncert: "NCERT 11 Ch 4 (Complex Numbers)",
    obj: "RD Sharma Objective: Complex Numbers; Cube Roots of Unity",
    prereq: ["Quadratic equations (M02)", "Trig identities (M07)"],
    speed: [
      "iⁿ: n mod 4 dekho. ω: 1+ω+ω² = 0, ω³ = 1.",
      "|z₁z₂| = |z₁||z₂|, arg(z₁z₂) = arg z₁ + arg z₂ — polar form me multiply/divide fast.",
    ],
    topics: [
      { name: "Complex Numbers", leaves: [
        ["Algebra, modulus & argument", 0.6, 2,
          "Operations, conjugate, modulus properties, principal argument by quadrant, square root of complex number.",
          "", "√(a+ib): (x+iy)² = a+ib compare karo."],
        ["Polar & Euler form, De Moivre (basic)", 0.3, 2,
          "r(cosθ + i sinθ), re^(iθ), powers using De Moivre.",
          "nth roots general theory deep.", ""],
        ["Cube roots of unity", 0.4, 2,
          "ω, ω², 1+ω+ω² = 0, factorisations like a³+b³ = (a+b)(a+bω)(a+bω²).",
          "nth roots of unity sums deep.", "ωⁿ: n mod 3."],
        ["Locus in complex plane (basic)", 0.2, 2,
          "|z−a| = r circle, |z−a| = |z−b| perpendicular bisector.",
          "Rotation theorem deep problems.", ""],
      ]},
    ],
  },

  /* ===================== ANALYTICAL ABILITY & REASONING ===================== */
  {
    id: "R01", subject: "R", name: "Series, Analogy & Classification",
    ncert: "", obj: "R.S. Aggarwal VR: Series Completion; Analogy; Classification",
    prereq: ["Squares 1–30, cubes 1–15, primes till 100", "Alphabet positions A=1…Z=26 and reverse (EJOTY: 5,10,15,20,25)"],
    speed: [
      "Series me order: difference → difference of difference → ratio → squares/cubes ± → alternate series.",
      "EJOTY trick se letter positions instant.",
    ],
    topics: [
      { name: "Series", leaves: [
        ["Number series", 2.5, 3,
          "Difference, ratio, squares/cubes, primes, alternate/two-series, mixed operations, wrong number find.",
          "", "45 sec rule: pattern na mile to skip, baad me aao."],
        ["Letter & alphanumeric series", 1.0, 2,
          "Letter jumps, repeating patterns, missing letters blocks.",
          "", ""],
      ]},
      { name: "Analogy & Classification", leaves: [
        ["Analogy (word, number, letter)", 1.0, 2,
          "Relation types (tool–worker, part–whole), number/letter analogies.",
          "", ""],
        ["Classification (odd one out)", 0.8, 1,
          "Words, numbers, letter groups.",
          "", ""],
      ]},
    ],
  },
  {
    id: "R02", subject: "R", name: "Coding, Blood Relations, Direction & Ranking",
    ncert: "", obj: "R.S. Aggarwal VR: Coding-Decoding; Blood Relations; Direction Sense; Logical Sequence/Ranking",
    prereq: ["Alphabet positions & opposite letters (A↔Z, B↔Y …)", "Pythagoras triplets (3-4-5, 5-12-13, 6-8-10)"],
    speed: [
      "Blood relation: family tree symbols (□ male, ○ female, = couple, | child) — kabhi dimaag me mat socho, likho.",
      "Direction: har turn paper pe arrow — 'left of facing direction' galti mat karo.",
    ],
    topics: [
      { name: "Coding–Decoding", leaves: [
        ["Letter/number shifting & substitution coding", 1.0, 2,
          "Shift patterns, reverse, opposite letters, positional value coding.",
          "", ""],
        ["Sentence/word coding (common word method)", 0.5, 2,
          "Find code of a word from multiple coded sentences.",
          "", "Common words ↔ common codes match karo."],
      ]},
      { name: "Blood Relations", leaves: [
        ["Blood relations (direct, puzzle & coded)", 1.5, 2,
          "Pointing-to-photo, coded relations (A+B means…), family puzzles.",
          "", ""],
      ]},
      { name: "Direction & Ranking", leaves: [
        ["Direction sense & distance", 1.2, 2,
          "Final direction, shortest distance, shadow-based direction (morning sun east).",
          "", "Morning me shadow west, evening me east."],
        ["Ranking & order", 1.0, 1,
          "Rank from top/bottom, total = L + R − 1, interchange positions.",
          "", "Total = left rank + right rank − 1."],
      ]},
    ],
  },
  {
    id: "R03", subject: "R", name: "Seating Arrangement & Puzzles",
    ncert: "", obj: "R.S. Aggarwal VR: Puzzle Test; Seating Arrangement + PYQ puzzles",
    prereq: ["Coding/ranking basics (R02)"],
    speed: [
      "Pehle definite info fix karo, fir 'possibilities' me 2 case banao — 3+ cases rarely needed.",
      "Table/grid banao — circular me facing centre vs outside likhna mat bhoolo.",
    ],
    topics: [
      { name: "Arrangements", leaves: [
        ["Linear seating arrangement", 1.3, 3,
          "Single row, two rows facing, left/right rules when facing north/south.",
          "", ""],
        ["Circular seating arrangement", 1.2, 3,
          "Facing centre/outside, neighbours, 'second to the left'.",
          "", "Facing centre: clockwise = left."],
      ]},
      { name: "Puzzles", leaves: [
        ["Floor/box, scheduling & attribute puzzles", 1.8, 3,
          "Grid puzzles with 2–3 attributes, day/month scheduling, floor-based puzzles.",
          "Very long bank-PO style 5-attribute puzzles (practise a few only).", ""],
        ["Mathematical operations & symbol substitution", 0.7, 1,
          "Symbol replacement (BODMAS), inequality symbols (>, ≥ coded).",
          "", ""],
      ]},
    ],
  },
  {
    id: "R04", subject: "R", name: "Logical & Critical Reasoning",
    ncert: "", obj: "R.S. Aggarwal VR: Syllogism; Statement–Conclusions/Assumptions/Course of Action; Data Sufficiency; Logical Venn Diagrams",
    prereq: ["Basic set/Venn understanding (M01)"],
    speed: [
      "Syllogism: Venn diagrams only — 'possibility' cases alag se.",
      "Data sufficiency: har statement ALAG check, fir combined. Answer calculate mat karo — sirf 'milega ya nahi'.",
    ],
    topics: [
      { name: "Deductive Reasoning", leaves: [
        ["Syllogism", 1.0, 2,
          "All/Some/No statements, definite vs possible conclusions, Venn method.",
          "", ""],
        ["Statements: conclusions, assumptions & course of action", 1.5, 2,
          "Implicit assumptions, strong/weak arguments, cause–effect.",
          "", "Extreme words (only, always) wale options aksar galat."],
        ["Critical reasoning (strengthen/weaken, inference)", 1.0, 2,
          "Identify conclusion, find assumption, strengthen/weaken.",
          "GMAT-level CR.", ""],
      ]},
      { name: "Data Sufficiency & Venn", leaves: [
        ["Data sufficiency", 1.5, 2,
          "Standard 5-option DS format for arithmetic, arrangement, relations.",
          "", ""],
        ["Logical Venn diagrams", 1.0, 1,
          "Represent relation between classes, count regions from Venn figures.",
          "", ""],
      ]},
    ],
  },
  {
    id: "R05", subject: "R", name: "Clocks, Calendars, Cubes & Visual Reasoning",
    ncert: "", obj: "R.S. Aggarwal VR: Clocks; Calendar; Cube & Dice; Non-Verbal (Mirror/Water Image, Series, Counting Figures, Paper Folding)",
    prereq: ["Remainders by 7", "Angle basics"],
    speed: [
      "Clock angle = |30H − 5.5M|.",
      "Calendar: odd days — normal year 1, leap 2; 100 years 5, 200 → 3, 300 → 1, 400 → 0.",
      "Dice: opposite faces nikalne ke liye common face wala rule.",
    ],
    topics: [
      { name: "Clocks & Calendars", leaves: [
        ["Clocks (angle, coincidence, gain/loss)", 0.8, 2,
          "Angle between hands, hands coincide/opposite/right angle count, faulty clocks.",
          "", "Hands coincide every 65 5/11 min."],
        ["Calendars (day of week, odd days)", 0.7, 2,
          "Day on a given date, repeating calendars, leap year rules.",
          "", ""],
      ]},
      { name: "Visual Reasoning", leaves: [
        ["Cubes & dice", 1.2, 2,
          "Painted cube counting (n³ small cubes), opposite faces of dice.",
          "", "3 faces painted = 8 corners; 2 faces = 12(n−2)."],
        ["Mirror/water image, figure series & paper folding", 1.5, 2,
          "Mirror & water images, embedded figures, figure series/analogy, paper folding & cutting.",
          "", ""],
        ["Counting figures (triangles, squares)", 1.0, 2,
          "Systematic counting of triangles, squares, rectangles.",
          "", "Grid m×n rectangles = ᵐ⁺¹C₂·ⁿ⁺¹C₂."],
      ]},
    ],
  },
  {
    id: "R06", subject: "R", name: "Quantitative Aptitude",
    ncert: "", obj: "R.S. Aggarwal Quantitative Aptitude: respective chapters",
    prereq: ["Percent ↔ fraction table (1/2 … 1/20)", "Tables till 25", "Squares till 30"],
    speed: [
      "Percent-fraction table ka use (12.5% = 1/8, 16.66% = 1/6) — calculation 3x fast.",
      "Time & work: LCM method (total work = LCM of days).",
      "Relative speed: same direction subtract, opposite add.",
    ],
    topics: [
      { name: "Arithmetic", leaves: [
        ["Number system (divisibility, HCF/LCM, remainders, unit digit)", 1.5, 2,
          "Divisibility rules, HCF/LCM word problems, remainder theorem basics, unit digit cyclicity, factors count.",
          "Advanced number theory (Fermat/Euler beyond basic).", "Unit digit: power ko 4 se divide karo."],
        ["Percentages", 1.0, 1,
          "Successive % change a+b+ab/100, population growth/depreciation.",
          "", "Successive: a + b + ab/100."],
        ["Profit, loss & discount", 1.0, 1,
          "CP/SP/MP relations, successive discounts, dishonest dealer.",
          "", ""],
        ["Ratio, proportion & ages", 1.0, 1,
          "Ratio combining, partnership, age problems.",
          "", ""],
        ["Averages & mixtures (alligation)", 0.8, 2,
          "Average change on adding/removing, alligation rule, replacement problems.",
          "", "Alligation cross-method."],
        ["Time & work, pipes & cisterns", 1.0, 2,
          "Efficiency/LCM method, work & wages, pipes with leak.",
          "", ""],
        ["Time, speed & distance (trains, boats)", 1.2, 2,
          "Average speed 2xy/(x+y), trains crossing, boats upstream/downstream, races.",
          "", "Avg speed same distance: 2xy/(x+y)."],
        ["Simple & compound interest", 0.6, 1,
          "SI, CI, difference between CI and SI for 2/3 years.",
          "", "CI − SI (2 yrs) = P(r/100)²."],
      ]},
    ],
  },
  {
    id: "R07", subject: "R", name: "Data Interpretation",
    ncert: "", obj: "R.S. Aggarwal QA: Data Interpretation (tables, bar, pie, line)",
    prereq: ["Percentages (R06)", "Approximation & fast division"],
    speed: [
      "Approximation: options door-door hon to calculate exact mat karo.",
      "Pie chart: 360° = 100%, 3.6° = 1%.",
    ],
    topics: [
      { name: "DI", leaves: [
        ["Tables, bar, pie & line graphs", 2.0, 2,
          "Percentage change, ratio, average from charts, mixed charts.",
          "Caselets of 10+ variables.", ""],
      ]},
    ],
  },

  /* ============================ COMPUTER AWARENESS ============================ */
  {
    id: "C01", subject: "C", name: "Number Systems & Data Representation",
    ncert: "", obj: "Claude notes + Morris Mano Digital Design Ch 1",
    prereq: ["Powers of 2 till 2¹⁶", "Nibble table 0000–1111 ↔ 0–F"],
    speed: [
      "Binary ↔ Hex: 4-bit groups; Binary ↔ Octal: 3-bit groups — decimal se hoke mat jao.",
      "Decimal → binary: powers of 2 subtract method (division se fast).",
    ],
    topics: [
      { name: "Conversions", leaves: [
        ["Binary, octal, hex & decimal conversions (integers)", 2.0, 2,
          "All 12 conversions, direct grouping, base-r to decimal, unknown base questions (e.g. (121)_b = 49).",
          "", "(121)_b = b² + 2b + 1 = (b+1)²."],
        ["Fractional number conversions", 0.8, 2,
          "Decimal fraction → binary (×2 method), binary fraction → decimal, hex fractions.",
          "", ""],
        ["Character codes: ASCII, BCD, Gray, Excess-3", 1.2, 2,
          "ASCII values (A=65, a=97, 0=48), BCD encoding, binary ↔ Gray, Excess-3.",
          "EBCDIC tables, Unicode internals.", "Gray: MSB same, fir XOR of adjacent bits."],
      ]},
      { name: "Signed Numbers & Binary Arithmetic", leaves: [
        ["Binary addition, subtraction, multiplication & division", 1.2, 1,
          "Column addition with carry, subtraction with borrow, simple multiply/divide.",
          "Booth's algorithm (basic awareness enough).", ""],
        ["Sign-magnitude, 1's & 2's complement (ranges)", 2.0, 3,
          "Representations, ranges for n bits: 2's −2ⁿ⁻¹ to 2ⁿ⁻¹−1, 1's/SM ±(2ⁿ⁻¹−1), subtraction via 2's complement, sign extension.",
          "", "2's complement: rightmost 1 tak same, uske baad sab flip."],
        ["Overflow detection", 0.5, 2,
          "Overflow when adding same-sign numbers gives opposite sign; carry-in ≠ carry-out of MSB.",
          "", ""],
      ]},
      { name: "Floating Point", leaves: [
        ["Normalised floating point & IEEE 754", 1.5, 3,
          "Mantissa/exponent, normalisation, bias (127 single, 1023 double), convert decimal ↔ IEEE 32-bit, special values.",
          "Denormal arithmetic rounding modes.", "Exponent stored = actual + 127."],
      ]},
    ],
  },
  {
    id: "C02", subject: "C", name: "Boolean Algebra & Logic Gates",
    ncert: "", obj: "Claude notes + Morris Mano Digital Design Ch 2–4 (selected)",
    prereq: ["Truth tables", "Set theory Venn (M01)"],
    speed: [
      "Simplify ke liye K-map > algebra (3–4 variables).",
      "Options me truth table ki 2–3 rows daal ke check karo — fastest.",
    ],
    topics: [
      { name: "Boolean Algebra", leaves: [
        ["Boolean laws, De Morgan & simplification", 1.5, 2,
          "Identity, complement, absorption, consensus, De Morgan, dual of expression.",
          "", "A + A'B = A + B."],
        ["SOP/POS, minterms & maxterms", 0.8, 2,
          "Canonical forms, Σm and ΠM notation, conversion.",
          "", ""],
        ["Karnaugh map (up to 4 variables)", 1.0, 2,
          "Grouping rules, don't-care conditions, minimal SOP.",
          "5–6 variable K-maps, Quine–McCluskey.", ""],
      ]},
      { name: "Logic Circuits", leaves: [
        ["Logic gates & universal gates", 1.2, 2,
          "AND/OR/NOT/NAND/NOR/XOR/XNOR truth tables, realising gates using only NAND/NOR (gate counts).",
          "CMOS transistor-level design.", "XOR using NAND = 4 gates."],
        ["Combinational circuits (adder, MUX, decoder)", 0.8, 1,
          "Half/full adder expressions, MUX/decoder/encoder basics.",
          "Carry look-ahead design details.", "Full adder Sum = A⊕B⊕C."],
        ["Flip-flops (basic)", 0.4, 1,
          "SR, JK, D, T characteristics.",
          "Sequential circuit design, state machines.", ""],
      ]},
    ],
  },
  {
    id: "C03", subject: "C", name: "Computer Organisation & General Awareness",
    ncert: "", obj: "Claude notes + NIMCET PYQs",
    prereq: ["Units: bit, byte, KB = 2¹⁰ B, MB = 2²⁰ B"],
    speed: ["Abbreviations & facts ka flashcard deck — roz 5 min."],
    topics: [
      { name: "Organisation", leaves: [
        ["CPU: ALU, CU, registers, instruction cycle & formats", 1.2, 2,
          "Components, fetch–decode–execute, instruction formats (0/1/2/3-address), addressing modes basics.",
          "Pipelining hazards deep.", ""],
        ["Memory hierarchy & memory units", 1.2, 2,
          "Registers > cache > RAM > disk, RAM/ROM types, address lines vs memory size (2ⁿ), cache hit ratio basic.",
          "Cache mapping numericals deep.", "n address lines ⇒ 2ⁿ locations."],
        ["I/O devices & backup storage", 0.5, 1,
          "Input/output devices, storage devices (HDD, SSD, optical, tape).",
          "", ""],
      ]},
      { name: "General", leaves: [
        ["OS, software, networking & abbreviations", 0.8, 1,
          "System vs application software, OS functions, compiler/interpreter/assembler, basic networking terms, common abbreviations.",
          "Deep OS/networking theory.", ""],
      ]},
    ],
  },

  /* ============================ GENERAL ENGLISH ============================ */
  {
    id: "E01", subject: "E", name: "Reading Comprehension",
    ncert: "", obj: "NIMCET PYQ passages + any editorial daily",
    prereq: ["Daily 1 editorial (10 min)"],
    speed: ["Pehle questions padho, fir passage — answer locate karo."],
    topics: [
      { name: "RC", leaves: [
        ["Reading comprehension", 2.5, 2,
          "Main idea, inference, vocab-in-context, tone.",
          "", ""],
      ]},
    ],
  },
  {
    id: "E02", subject: "E", name: "Vocabulary",
    ncert: "", obj: "Word Power Made Easy + PYQ word lists",
    prereq: ["Roots: bene, mal, chron, graph, anti, ante …"],
    speed: ["Root words se unknown words guess — 1 root = 10 words."],
    topics: [
      { name: "Word Power", leaves: [
        ["Synonyms", 1.5, 2, "High-frequency exam words, roots.", "Rare GRE-only words.", ""],
        ["Antonyms", 1.5, 2, "High-frequency exam words, prefixes (un-, dis-, in-).", "", ""],
        ["Idioms & phrases, one-word substitution", 1.5, 1, "Common idioms, one-word substitutes list.", "", ""],
      ]},
    ],
  },
  {
    id: "E03", subject: "E", name: "Grammar & Usage",
    ncert: "", obj: "Wren & Martin (articles, prepositions, tenses, SVA chapters)",
    prereq: [],
    speed: ["Error spotting: subject–verb agreement pehle check karo, fir tense, fir preposition."],
    topics: [
      { name: "Grammar", leaves: [
        ["Articles & prepositions", 1.2, 1, "a/an/the rules, common preposition usages.", "", ""],
        ["Verbs, tenses & subject–verb agreement", 0.8, 2, "Tense consistency, SVA rules with each/either/neither.", "", ""],
        ["Error spotting, sentence improvement & fill in the blanks", 1.0, 2, "Common error types; technical writing basics.", "", ""],
      ]},
    ],
  },
];

// Global speed / pre-requisite kit — practised as daily 5-minute drills.
const SPEED_KIT = [
  { id: "sq", name: "Squares 1–30", how: "Roz 2 min: random 10 numbers bolo. Target: <2 sec each." },
  { id: "cu", name: "Cubes 1–20", how: "Roz 1 min random 5." },
  { id: "p2", name: "Powers of 2 (to 2¹⁶) & 3 (to 3⁸)", how: "Computer + P&C + binomial me daily use." },
  { id: "frac", name: "Fraction ↔ percent (1/2 … 1/20)", how: "1/7 = 14.28%, 1/8 = 12.5%, 1/9 = 11.11% … DI & aptitude ke liye." },
  { id: "fact", name: "Factorials till 10!", how: "P&C/probability me instant." },
  { id: "trig", name: "Trig values table + ASTC + allied angles", how: "15°, 18°, 36°, 22.5° values bhi." },
  { id: "log", name: "log 2, 3, 5, 7 values", how: "0.3010, 0.4771, 0.6990, 0.8451 — digits count questions." },
  { id: "root", name: "√2, √3, √5, √6, √7 (3 decimals)", how: "1.414, 1.732, 2.236, 2.449, 2.646 — approximation." },
  { id: "lim", name: "Standard limits card", how: "Calculus start se pehle." },
  { id: "der", name: "Standard derivatives & integrals table", how: "Calculus ke dauran roz 2 min." },
  { id: "hex", name: "Binary nibble ↔ hex table (0000–1111)", how: "Computer section ka base." },
  { id: "vedic", name: "Fast multiplication (base method, ×11, ×5, squares ending in 5)", how: "Roz 5 random multiplications." },
  { id: "elim", name: "Option elimination techniques", how: "Value putting, extreme cases, dimension/units check, symmetry — har mock me consciously use." },
];

// Problem-solving protocol per depth level (think time before hint).
const PROTOCOL = [
  { level: "D1 · Basic", think: "2 min", steps: [
    "Question padho, 'kya diya / kya chahiye' 1 line me likho.",
    "2 min tak solve karo. Formula yaad nahi → formula sheet dekho (solution NAHI).",
    "Galat/stuck → solution dekho, turant bina dekhe dobara solve karo.",
  ]},
  { level: "D2 · Standard", think: "5 min", steps: [
    "5 min socho: kaunsa concept? 2 approaches likho.",
    "Stuck → HINT only (solution ki pehli line / Claude 'hint only' prompt). Fir 5 min aur.",
    "Fir bhi nahi → full solution padho, band karo, khud se likho.",
    "Question ko ⟳ Re-solve list me daalo (Mistakes tab) — 3 din baad bina dekhe.",
  ]},
  { level: "D3 · Deep", think: "8–10 min", steps: [
    "8–10 min: diagram/cases/special values try karo. Kam se kam 2 approaches.",
    "Hint 1 → 5 min → Hint 2 → 5 min.",
    "Solution padho: 'kaunsi key idea miss hui?' 1 line me likho (Mistake log).",
    "Same type ka 1 aur question turant solve karo. 3 aur 7 din baad re-solve.",
  ]},
  { level: "Mock / Timed", think: "Maths ≤ 84 sec · Reasoning ≤ 45 sec · Computer/English ≤ 30–60 sec", steps: [
    "3-pass: Pass 1 easy (sure-shot) → Pass 2 medium → Pass 3 hard only if time.",
    "Guess sirf tab jab 2 options eliminate ho gaye (−25% negative).",
    "Kisi question pe time limit cross → mark & move. Ego nahi.",
  ]},
];

// Revision types used by the planner.
const REVISION_TYPES = [
  { name: "Same-day recap (Blurting)", when: "Har study session ke end me 5 min", how: "Kitaab band, jo padha sab blank page pe likho. Jo bhool gaye unhe red se mark karo." },
  { name: "Spaced revision (1-3-7-15-30-60)", when: "Roz Pomodoro 1 (auto from tracker)", how: "Tracker 'Due today' list deta hai. Har item: 2 min blurt → 2 min formula/notes check → 3 Qs → rating (Again/Hard/Good/Easy)." },
  { name: "Tough-topic revision", when: "Roz 1 item + shorter intervals (1-2-4-7-12-20-30)", how: "Tough mark kiye topics zyada baar aate hain. Har baar 1 naya question + 1 purana galat question." },
  { name: "Mistake-log re-solve", when: "Roz Pomodoro 1 me 1–2 items", how: "Galat questions 1-3-7-21 din pe bina solution dekhe dobara. 4 baar sahi → resolved." },
  { name: "Weekly revision", when: "Har Sunday (2 hr)", how: "Is hafte ke sab subtopics + formula sheet + mistake log + 20 mixed timed Qs." },
  { name: "Monthly revision test", when: "Mahine ka last Sunday", how: "Mahine ke chapters ka 30-Q timed test + analysis. Weak subtopics tough list me daalo." },
  { name: "Pre-mock revision", when: "Mock se pehle din 20 min", how: "Formula sheets + top 10 mistakes." },
  { name: "Final revision", when: "Exam se pehle last 14 din", how: "Sirf formula sheets, mistake log, tough topics, 1 mock / 2 din. Naya kuch nahi." },
];

// Pomodoro cues for a revision pomodoro (25 min).
const REVISION_POMODORO = [
  { at: 0, text: "0–3 min: Blurt — bina dekhe sab likho (formulas, types)." },
  { at: 3, text: "3–8 min: Notes / formula sheet se check, gaps red me." },
  { at: 8, text: "8–21 min: 4–6 questions (PYQ + purane galat)." },
  { at: 21, text: "21–25 min: Tracker me rating + mistake log update." },
];

// Mistake types for mock / practice analysis.
const MISTAKE_TYPES = [
  "Concept gap", "Formula bhool gaya", "Calculation error", "Silly / misread",
  "Time pressure", "Wrong guess", "Skipped but could solve", "Approach nahi soojha", "Topic abhi padha nahi",
];

// Mock phase settings.
const MOCK_PLAN = {
  reservedPyqYears: ["2025", "2024", "2023", "2022", "2021", "2020"],
  mockCount: 30,
};
