/*
 * NIMCET 2026 (6 June 2026) — actual paper, all 120 questions.
 *
 * Source: candidate response sheet (official CBT paper). Question and option
 * images are re-assembled from the sheet's own images into pyq/2026/q<n>.webp
 * WITHOUT the answer ticks, the candidate details or the watermark.
 * The official key (green tick) was re-solved question by question:
 * `ans` is the verified answer; `off` is the official key where it differs;
 * `flag` explains a flawed question or key.
 *
 * Row: [n (1–120), leaf id, depth asked (1–3), ans, key idea, common trap, flag?, off?]
 */
const PYQ_2026_ROWS = [
  // ===== Mathematics (paper Q1–50) =====
  [1, "M01:set-operations-symmetric-difference-venn-diagram", 2, "C",
    "(A∆B)∩C = (A∩C)∆(B∩C). (A∩B)ᶜ∩C me wo elements bhi hain jo C me hain par A aur B dono me nahi.",
    "Har option ka Venn region shade karo — algebra me time mat lagao."],
  [2, "M01:types-of-relations-reflexive-symmetric-transitiv", 2, "C",
    "3 | (a − 2b) ⟺ a + b ≡ 0 (mod 3) ⇒ symmetric. a ~ a sirf a ≡ 0 ⇒ not reflexive. 1 ~ 2, 2 ~ 1 par 1 ≁ 1 ⇒ not transitive.",
    "−2b ≡ b (mod 3) wala simplification na dekhna; transitive ka counter-example na banana."],
  [3, "M01:one-one-onto-bijection-counting-functions", 2, "B",
    "Even 2, 4 → {2, 4, 6, 8}: 4 × 3 = 12. Odd 1, 3 → baaki 6 me se: 6 × 5 = 30. n = 360 = 2³·3²·5 ⇒ a + b + c = 6.",
    "Odd elements ko bhi sirf odd numbers pe bhejna — unpe koi restriction nahi, bas injective."],
  [4, "M01:set-operations-symmetric-difference-venn-diagram", 1, "D",
    "n sets ke Venn diagram me regions = 2ⁿ (bahar wala region bhi). 2⁵ = 32.",
    "Outside region na ginna (31) — options me 32 hi hai."],
  [5, "M01:cartesian-product-cardinality", 3, "C",
    "R_a ⊆ ℕ infinite ⇒ countable; R ⊆ ℕ × ℕ bhi countable ⇒ same cardinality. (A) galat: kuch R_a khaali ho sakte hain (partial function).",
    "'Infinite' ko 'bada' samajhna — ℕ aur ℕ × ℕ dono countable hain."],
  [6, "M01:set-operations-symmetric-difference-venn-diagram", 3, "B",
    "Har element ke (A, B, C) membership: A∩B me ⇒ C me (1 way); kisi me nahi ⇒ C me nahi (1); sirf ek me ⇒ C me ho ya na ho (2 × 2). Total 6 ⇒ 6ⁿ.",
    "8 cases me se invalid cases hatana bhool jaana. Element-wise counting best."],
  [7, "M01:statements-connectives-truth-tables", 1, "D",
    "(¬p ∨ q) ⇒ r false sirf jab (¬p ∨ q) true aur r false. (¬p ∨ q) 3 rows me true ⇒ 3 false rows ⇒ 8 − 3 = 5.",
    "Implication ka truth table: sirf T ⇒ F false hota hai."],
  [8, "M05:independent-events", 1, "B",
    "P(neither) = (1 − 2/5)(1 − 3/4) = 3/5 × 1/4 = 3/20.",
    "1 − P(X) − P(Y) karna — independent me product lo."],
  [9, "M05:addition-rule-complement-mutually-exclusive-even", 1, "A",
    "Complement: P = 1 − P(first ≥ 4 aur second < 4) = 1 − ½ · ½ = 3/4.",
    "'Less than 4' aur 'at least 4' ko mix karna; overlap minus na karna."],
  [10, "M05:conditional-probability-multiplication-rule", 1, "A",
    "Multiplication rule: P(A₁A₂A₃) = P(A₁) P(A₂|A₁) P(A₃|A₁∩A₂).",
    "Conditional ka order ulta likhna."],
  [11, "M11:variance-standard-deviation-incl-origin-scale-ch", 2, "A",
    "Mean = 110.5/7 = 15.79. Σ(x − x̄)² ≈ 6.21. Sample SD = √(6.21/(7 − 1)) ≈ 1.02.",
    "'Sample' SD me n − 1 se divide karna hai; n se karoge to 0.94 aata hai."],
  [12, "M11:median-mode", 1, "C",
    "Modal class 30–35: Mode = 30 + (20 − 14)/(2·20 − 14 − 18) × 5 = 30 + 3.75 = 33.75.",
    "Denominator 2f₁ − f₀ − f₂ galat lena."],
  [13, "M11:mean-arithmetic-weighted-combined", 1, "B",
    "Mode = x hone ke liye x repeat ho; mean (80 + x)/9 = x ⇒ x = 10; median bhi 10.",
    "Options daal ke 10 sec me check — mean, median, mode teeno."],
  [14, "M05:independent-events", 1, "D",
    "Z = XY = 1 sirf jab X = Y = 1 ⇒ ¼; P(Z = 0) = ¾.",
    "Bernoulli / random-variable shabd dekh ke ghabrana — ye bas independent events hai."],
  [15, "M11:moments-about-mean-origin", 1, "D",
    "β₂ = μ₄/μ₂² = 63/9 = 7 > 3 ⇒ Leptokurtic.",
    "β₂ = 3 mesokurtic, > 3 lepto, < 3 platy — classification yaad na hona."],
  [16, "M03:harmonic-progression", 1, "B",
    "a + b = 10, H.M. = 2ab/(a + b) = 3.2 ⇒ ab = 16 ⇒ 2 aur 8.",
    "H.M. = ab/(a + b) likhna (2 bhool jaana)."],
  [17, "M03:ap-nth-term-sum", 2, "B",
    "S₁₁ = 11·T₆ = 88 ⇒ T₆ = 8 ⇒ T₁₀ = 14, T₁₁ = 15.5. Sum = p/3 ⇒ p = 88.5; product = q/3 ⇒ q = 651 ⇒ q − 2p = 474.",
    "Leading coefficient 3 bhool ke sum = p, product = q le lena."],
  [18, "M04:coefficient-of-x-term-independent-of-x", 2, "A",
    "(x² + 1/x)¹² me power 24 − 3r; (x + 1/x²)¹² me 12 − 3r. 10 ke liye dono me r integer nahi ⇒ 0.",
    "r fraction aane pe bhi coefficient nikalne lagna."],
  [19, "M06:evaluation-properties-of-determinants", 2, "A",
    "R₂ − R₁, R₃ − R₂ se x khatam ⇒ determinant constant. x = 0 pe = −1.",
    "x = 2026 daal ke expand karna — pehle row operations."],
  [20, "M06:system-of-linear-equations-cramer-consistency", 2, "C",
    "Non-trivial ⟺ det = 0 ⇒ 2(sin θ + cos θ)(sin θ − cos θ) = 0 ⇒ tan θ = ±1 ⇒ 4 values.",
    "Sirf tan θ = 1 lena."],
  [21, "M03:n-n-n-and-series-built-from-them", 2, "C",
    "A_k = (1² + … + k²)/k = (k + 1)(2k + 1)/6 ⇒ 6A_k − 3k = 2k² + 1; Σ = 31 ⇒ n = 3.",
    "A_k me k se divide karna bhool jaana (mean hai, sum nahi)."],
  [22, "M02:forming-equations-transformed-roots", 2, "D",
    "y = (α + 2)/(α − 1) ⇒ α = (y + 2)/(y − 1). ax² + bx + c me daalo ⇒ (a+b+c)y² + (4a+b−2c)y + (4a−2b+c) = 0.",
    "Substitution ulta karna — α ko y me express karo."],
  [23, "M02:laws-of-indices-exponentials-exponential-equatio", 2, "C",
    "2^(x + 2y − 7/6) = 3^(x + 2y − 7/6) ⇒ exponent 0 ⇒ 6x + 12y − 7 = 0.",
    "Alag bases equal tabhi jab exponent 0 — ye rule yaad na hona."],
  [24, "M02:algebraic-identities-expansions", 3, "B",
    "a = √(x + y), b = √(y + z): 2a − 3b = 2 aur 4a² − 9b² = 8 ⇒ 2a + 3b = 4 ⇒ a = 3/2, b = 1/3 ⇒ √((20a² + 18b² + 1)/(9b² + 2)) = √16 = 4.",
    "Substitution na karna — 3 variables me ulajh jaana. (a² − b²) factorisation dekho."],
  [25, "M03:n-n-n-and-series-built-from-them", 3, "B",
    "n odd: Σ(−1)^(k−1)k = (n + 1)/2, Σ(−1)^(k−1)k² = n(n + 1)/2 ⇒ (n+1)²/4 − n(n+1)/2 + 2450 = 0 ⇒ n² = 9801 ⇒ n = 99.",
    "Even/odd n ke alag formulas na lena. Even n se koi solution nahi."],
  [26, "M06:system-of-linear-equations-cramer-consistency", 2, "D",
    "Vandermonde pattern (2², 3², 4² → 5²): x = (25 − 9)(25 − 16)/((4 − 9)(4 − 16)) = 144/60 = 36/15.",
    "Pura Cramer determinant banana — pattern pehchano."],
  [27, "M08:forms-of-equation-of-a-line", 1, "D",
    "|x| = |y|: y = x ⇒ 5x = 11 (integer nahi); y = −x ⇒ x = 1, y = −1 ⇒ IV quadrant.",
    "Sirf y = x case lena."],
  [28, "M08:distance-section-formula-centroid-incentre-area", 1, "B",
    "Midpoints se vertices B(−3, 0), C(3, 4). Area = ½|1(0 − 4) − 3(4 − 2) + 3(2 − 0)| = 2.",
    "Midpoint triangle ka area le lena — pehle vertices nikalo."],
  [29, "M08:standard-general-equation-of-circle", 1, "C",
    "Diameters ka intersection = centre (2, −1); πr² = 153.94 ⇒ r = 7 ⇒ x² + y² − 4x + 2y − 44 = 0.",
    "Centre (−g, −f) ke sign ulte."],
  [30, "M08:parabola-tangent-normal-parametric-form", 2, "C",
    "y = mx + c: dono parabolas ke saath D = 0 ⇒ c = m²/4 aur (m + 4)² = 4(4 − c) ⇒ m = −4, c = 4.",
    "Sirf ek parabola pe condition lagana. Options dono pe check karo."],
  [31, "M08:ellipse-tangent-normal-parametric-form", 2, "D",
    "a/e = 4, e = ½ ⇒ a = 2, b² = 3. Normal: a²x/x₁ − b²y/y₁ = a² − b² ⇒ 4x − 2y = 1.",
    "Tangent aur normal ka slope mix karna."],
  [32, "M08:hyperbola-tangent-normal", 3, "B",
    "Hyperbola ka koi bhi tangent + dono asymptotes ⇒ triangle area = ab = a². (Tangent x = a: (0,0), (a, a), (a, −a).)",
    "Intersection nikalne me galti — 'area = ab' result yaad rakho."],
  [33, "M01:composition-inverse-of-functions", 2, "C",
    "h = 1 ⟺ |g(x)| ≤ 1. |x| ≤ 2 pe |2 − x²| ≤ 1 ⇒ 1 ≤ |x| ≤ √3; |x| > 2 pe g = 2 ⇒ h = 0.",
    "g ke dono pieces check na karna."],
  [34, "M09:l-hospital-s-rule-series-expansions", 2, "A",
    "x² + 2cos x − 2 ≈ x⁴/12; x sin³x ≈ x⁴ ⇒ 1/12.",
    "cos x ka x⁴/24 term chhod dena — expansion 3 terms tak."],
  [35, "M09:standard-limits-algebraic-limits", 1, "C",
    "√x dono taraf se bahar ⇒ 1/√(1 + √(1/x + …)) → 1.",
    "Highest power compare na karna."],
  [36, "M09:tangents-normals", 2, "C",
    "Intersection x = 1, 4. x = 1 pe slopes −2, 4 ⇒ tan θ = |(−2 − 4)/(1 − 8)| = 6/7.",
    "1 + m₁m₂ ka sign; |…| bhool jaana."],
  [37, "M09:definite-integrals-properties", 1, "D",
    "sec⁴x = (1 + tan²x) sec²x; t = tan x ⇒ ∫₀¹(1 + t²)dt = 4/3.",
    "sec² ko dt ke liye na bachana."],
  [38, "M09:definite-integrals-properties", 3, "A",
    "f⁻¹(y) = √((1 + y)/(1 − y)). y = cos φ ⇒ ∫₀^π 2cos²(φ/2) dφ = π.",
    "f⁻¹ ka domain ulta lena. Shortcut: ∫f⁻¹ = rectangle − ∫f."],
  [39, "M09:standard-limits-algebraic-limits", 1, "A",
    "log(1 + |sin 2x|) ≈ 2|x| ⇒ 2x²/(x²(|x| + 3)) → 2/3.",
    "|x| dekh ke 'limit exist nahi karti' bol dena."],
  [40, "M09:maxima-minima", 2, "B",
    "x < −1 wale piece me f′ = 0 at x = (−1 − √3)/2 ≈ −1.37 ⇒ local maxima (−2, −1) me. x = −1 pe global min 0.",
    "|x + 1| ka corner aur dono pieces alag na dekhna."],
  [41, "M09:continuity-differentiability", 3, "A",
    "(1 + x)^(1/3) − (1 + 2x)^(1/4) = −x/6 + (19/72)x² ⇒ a = −1/6, f′(0) = 19/72 ⇒ 7/72.",
    "Binomial expansion ka x² coefficient galat."],
  [42, "M01:composition-inverse-of-functions", 2, "A",
    "f = (3x + 1)/(x + 2); f(3) = 2, f′(3) = 5/25 ⇒ (f⁻¹)′(2) = 1/f′(3) = 5.",
    "f′ ko x = 2 pe nikalna — us x pe nikalo jaha f(x) = 2."],
  [43, "M07:multiple-sub-multiple-angles", 2, "D",
    "cos 6x = 32c⁶ − 48c⁴ + 18c² − 1 ⇒ a + b + c = 2. Shortcut: x = 0 ⇒ a+b+c+d = 1; x = π/2 ⇒ d = −1.",
    "Pura expansion karna — special values daalo."],
  [44, "M07:compound-angle-identities", 2, "A",
    "x(1 − tan25° tan35°) = y(tan25° + tan35°) ⇒ x = y tan60° = √3·y.",
    "tan(A + B) form pehchanna hi trick hai.",
    "x = √3·y se 'x > y' tabhi sahi jab y > 0 (y ≤ 0 pe nahi). Question strictly flawed hai; official key A rakha hai."],
  [45, "M07:general-solutions-of-trig-equations", 1, "D",
    "cos(x/2) = ½, x/2 ∈ [0, 2π] ⇒ x/2 = π/3, 5π/3 ⇒ 2 points.",
    "x ka interval x/2 ke interval me convert na karna."],
  [46, "M07:sine-rule-cosine-rule-projection-formula", 2, "D",
    "Napier: (a − b)/(a + b) = tan((A − B)/2)·tan(C/2) = cot((A + B)/2)·tan((A − B)/2). (D) me tan(C/2) se divide hai ⇒ galat.",
    "Napier analogy ka tan/cot ulta yaad hona."],
  [47, "M07:sine-rule-cosine-rule-projection-formula", 1, "A",
    "AB² = 60² + 80² − 2·60·80·cos60° = 5200 ⇒ 20√13.",
    "cos 60° = √3/2 le lena."],
  [48, "M07:heights-distances", 1, "A",
    "45° ⇒ distance 80. Top: 80 − h = 80 tan30° ⇒ h = 80(1 − 1/√3).",
    "Diagram na banana."],
  [49, "M07:domain-range-principal-values", 1, "B",
    "cos⁻¹(cos(−π/6)) = π/6; sin⁻¹(sin 5π/6) = π/6 ⇒ π/3.",
    "sin⁻¹(sin 5π/6) = 5π/6 likhna — principal range [−π/2, π/2]."],
  [50, "M07:inverse-trig-identities-basic-simplification", 1, "C",
    "5x/(1 − 6x²) = 1 ⇒ x = 1/6 ya −1. x = −1 pe LHS = −3π/4 ⇒ sirf 1 solution.",
    "Dono roots accept kar lena — principal value check."],
  // ===== Analytical Ability & Logical Reasoning (paper Q1–40) =====
  [51, "R02:blood-relations-direct-puzzle-coded", 2, "C",
    "Mira ki saas ki maa = meri dadi/nani ⇒ saas = meri maa ya bua/maasi. Maa ke saare bachche unmarried ⇒ saas aunt hai ⇒ Mira aunt ke bete ki wife.",
    "Option D (brother's wife) — 'mother's offsprings unmarried' clue miss karna."],
  [52, "R03:floor-box-scheduling-attribute-puzzles", 3, "A",
    "Tech = 2, G Travel, C–B saath (Tech nahi), A Beauty nahi, F A/B me se ek ke saath, Travel nahi. Ek valid arrangement: Travel {G, A}, Tech {D, E}, Beauty {B, C, F}.",
    "Conditional 'If D Tech then E Tech' ko ulta lagana; options se eliminate karo."],
  [53, "R04:statements-conclusions-assumptions-arguments", 2, "B",
    "Experiment-based education ki kami Science/Maths ki weakness se seedha judi hai ⇒ II.",
    "Course of action ko 'reason' ki tarah judge karna."],
  [54, "R06:ratio-proportion-ages", 1, "B",
    "x : y : z = 10 : 15 : 24 (49 parts) ⇒ y = 98 × 15/49 = 30.",
    "Ratios ko common term pe match na karna."],
  [55, "R06:ratio-proportion-ages", 2, "C",
    "S_runs = L_balls + 10, S_balls = L_runs − 5, S_runs + L_runs = 105, S_balls = L_balls − 10 ⇒ L_balls = 50 ⇒ S_runs = 60.",
    "Runs aur balls ke 4 variables mix karna — table banao."],
  [56, "R06:ratio-proportion-ages", 2, "B",
    "c + w + u = 160; c − w/4 − u/2 = 79; c − w/2 − u/4 = 76 ⇒ w − u = 12 ⇒ u = 24 ⇒ c = 100.",
    "Dono schemes subtract karke shortcut na lena."],
  [57, "R06:averages-mixtures-alligation", 1, "D",
    "A = 10600 − 3000 = 7600, B = 10600 − 9660 = 940, C = 10600 − 9540 = 1060 ⇒ D = 1000.",
    "Average × 3 karna bhool jaana."],
  [58, "R06:percentages", 1, "B",
    "Both = 20% of 1001 = 200.2 = 70% of cat owners ⇒ 286.",
    "70% ko dog owners pe lagana."],
  [59, "R04:critical-reasoning-strengthen-weaken-inference", 1, "B",
    "Circular argument: conclusion hi reason ban jata hai ('free speech important hai kyunki log bolna chahte hain').",
    "Bandwagon (C) ya affirming the consequent (A) ko circular samajhna."],
  [60, "R02:letter-number-shifting-substitution-coding", 1, "A",
    "Vowels +2: O → Q (17), I → K (11). LOGIC ⇒ 12-17-7-11-3.",
    "Sirf ek vowel shift karna."],
  [61, "R03:linear-seating-arrangement", 2, "B",
    "W V _ _ _ _, ZU saath, Y Z se pehle, X end pe nahi ⇒ Y X Z U ya X Y Z U ⇒ 4th = X ya Y.",
    "Saare cases na banana."],
  [62, "R04:syllogism", 2, "D",
    "Definite: kuch compounds plastic nahi. Plastics → synthetic, polymers → compounds.",
    "'Must be false' me possibility aur definite mix karna.",
    "Strictly koi option 'must be false' sabit nahi hota ('All compounds are synthetic' bhi possible hai). Official key D rakha hai."],
  [63, "R04:logical-venn-diagrams", 1, "C",
    "Total = 70 + 100 + 30 + 150 = 350; hockey = 100 ⇒ 28.57%.",
    "'Only hockey' (70) ko hockey players maan lena."],
  [64, "R04:syllogism", 1, "A",
    "Some professors are doctors + all doctors are patients ⇒ some professors are patients.",
    "II possibility hai, definite nahi."],
  [65, "R04:critical-reasoning-strengthen-weaken-inference", 2, "D",
    "Passage: Code on Social Security central level pe bana, states uske cue se rules notify karte hain ⇒ D.",
    "B me 'each platform' — passage kehta hai workdays cumulative hain."],
  [66, "R05:mirror-water-image-figure-series-paper-folding", 2, "A",
    "Har step me chaaron symbols clockwise ek khaana aage. Agla: TL ⊗|, TR ⊗(neeche line), BL ⊗̄, BR boxed ⊕.",
    "Symbol badalna dhundna — sirf position rotation hai."],
  [67, "R01:number-series", 1, "A",
    "n | n³: 2|8, 3|27, 4|64, 5|125 ⇒ 6|216.",
    "Digits ko ek number samajh ke difference lena."],
  [68, "R02:letter-number-shifting-substitution-coding", 1, "B",
    "INDIA → JLGEF: +1, −2, +3, −4, +5 ⇒ ROME → SMPA.",
    "Alternating +/− ko sirf + samajhna."],
  [69, "R07:tables-bar-pie-line-graphs-data-visualization", 2, "B",
    "Profit = Revenue − Cost. A: 12 → 26 (~117%); B: 25 → 69 (~176%) ⇒ B.",
    "Revenue growth ko profit growth samajhna."],
  [70, "R03:floor-box-scheduling-attribute-puzzles", 1, "D",
    "Read-only: Q, R, T, U. Excel: S, T, U. Local only (backup nahi): R, T, U ⇒ T aur U.",
    "Teen conditions ka intersection na lena."],
  [71, "R04:syllogism", 1, "C",
    "All Z are Y + no Y is X ⇒ no Z is X (II). I definite nahi.",
    "'Every X is W' se Z–W link maan lena."],
  [72, "R06:ratio-proportion-ages", 1, "B",
    "h = r: cylinder πr³, cone πr³/3, hemisphere 2πr³/3 ⇒ 3 : 1 : 2.",
    "Hemisphere volume (2/3)πr³ yaad na hona."],
  [73, "R06:number-system-divisibility-hcf-lcm-remainders-un", 1, "A",
    "AP 72, 69, …, 3: 24 terms ⇒ sum = 12 × 75 = 900.",
    "Last positive term 3 hai, 0 nahi."],
  [74, "R01:number-series", 3, "A",
    "Grid me row-wise operation dhundo; 2–3 rows pe rule test karo.",
    "Ek row pe fit rule ko baaki pe check na karna.",
    "Humein koi consistent rule nahi mila jo saari rows pe fit ho. Official key 34 (A) rakha hai — exam me aisa question skip karna smart hai."],
  [75, "R02:direction-sense-distance", 1, "A",
    "W → (left) S → (right) W → (right) N → (left) W → (right) N.",
    "Distances bekaar hain — sirf turns track karo."],
  [76, "R03:circular-seating-arrangement", 3, "D",
    "Finance Arjun ke 3rd left = opposite. Marketing–HR opposite pair. Bhavesh Devika (Ops) aur Strategy ke beech ⇒ Farah Finance (Analytics se 2nd right).",
    "Opposite pairs (6 seats me 3 door) use na karna."],
  [77, "R06:averages-mixtures-alligation", 1, "C",
    "4X = 84 ⇒ X = 21; 4.2Y = 84 ⇒ Y = 20; 1.2W = 16.8 ⇒ W = 14; Z = 29.",
    "320% ⇒ total = 4.2Y wala step miss."],
  [78, "R06:percentages", 1, "A",
    "Reduction = 16/116 × 100 = 13.79%.",
    "16% hi bol dena."],
  [79, "R07:tables-bar-pie-line-graphs-data-visualization", 1, "C",
    "350 g C: protein 70, fat 35 — sabse zyada protein (tie) aur sabse kam fat.",
    "Sirf protein dekhna (D me bhi 70 hai par fat 65)."],
  [80, "R04:statements-conclusions-assumptions-arguments", 2, "D",
    "Rule: max 1 hour. Shailaja ≥ 1.5 hour se hai ⇒ agar rule nahi tod rahi to wo Crossroads me nahi ho sakti.",
    "Contrapositive na pehchanna."],
  [81, "R02:ranking-order", 1, "A",
    "Total = 35 + 32 − 1 = 66.",
    "−1 bhool jaana."],
  [82, "R03:input-output-machine-input-rearrangement", 2, "B",
    "X: 2 → 4 → 10 → 30 → 105 → 420 → 1890 → 9450 (Y: 4, 5, 6, …). 9450 ≥ 3000 pe stop.",
    "Y ko update kiye bina X update karna (order)."],
  [83, "R06:simple-compound-interest", 2, "C",
    "Equal SI: P₁·2 = P₂·3 = P₃·4 ⇒ P ∝ ½ : ⅓ : ¼ = 6 : 4 : 3.",
    "Ratio ulta 2 : 3 : 4 lena."],
  [84, "R02:blood-relations-direct-puzzle-coded", 2, "A",
    "P3–P2 grandparents, P1 unki beti aur P6 ki wife, P4/P5/P7 bachche ⇒ P1 mother, P4 daughter.",
    "Gender count (2 fathers, 2 mothers…) use na karna."],
  [85, "R03:linear-seating-arrangement", 1, "B",
    "Bottom se: T, P, S, R, Q ⇒ Q top.",
    "Clues order me na lagana."],
  [86, "R02:blood-relations-direct-puzzle-coded", 1, "B",
    "Father's only son = Arun khud ⇒ uski beti.",
    "'Only son' ko brother samajhna."],
  [87, "R06:ratio-proportion-ages", 1, "A",
    "A = 2B, A − 5 = 3(B − 5) ⇒ B = 10, A = 20.",
    "5 saal dono ke age se na ghatana."],
  [88, "R05:clocks-angle-coincidence-gain-loss", 1, "C",
    "Next 9:45, interval 45 ⇒ previous 9:00; wo 15 min pehle gayi ⇒ abhi 9:15.",
    "Previous train ka time hi answer bol dena."],
  [89, "R06:averages-mixtures-alligation", 1, "C",
    "t = (3600 + t)/10 + 900 ⇒ 9t = 12600 ⇒ 1400.",
    "Average me 10th person ko shamil na karna."],
  [90, "R06:averages-mixtures-alligation", 2, "A",
    "Alcohol: A 5/8, B 1/4, target 1/2 ⇒ alligation (1/2 − 1/4) : (5/8 − 1/2) = 2 : 1 ⇒ A = 2/3 × 2.1 = 1.4 L.",
    "Alligation me ratio ulta lena."],
  // ===== Computer Awareness (paper Q1–20) =====
  [91, "C01:sign-magnitude-1-s-2-s-complement-ranges", 1, "C",
    "n-bit 2's complement range −2ⁿ⁻¹ … 2ⁿ⁻¹ − 1 ⇒ 8-bit min −128.",
    "1's complement (−127) ya unsigned se mix."],
  [92, "C03:input-output-storage-backup-devices", 2, "D",
    "Head move kiye bina ek cylinder = 4 surfaces ka same track ⇒ 4 × 2000 = 8000 sectors.",
    "Total tracks multiply kar dena."],
  [93, "C04:operating-systems-windows-macos-linux-android", 2, "C",
    "Virtual memory ka fayda sirf extra space nahi — har process ko alag address space (protection / isolation) milta hai.",
    "'RAM kaafi hai to VM bekaar' (B) maan lena."],
  [94, "C04:system-software-utilities-device-drivers-applica", 2, "D",
    "DLL ke fayde: bug fixes milte hain, exe chhoti, RAM share hoti hai — A, B, C teeno galat ⇒ None.",
    "Static vs dynamic linking ke fayde ulte yaad hona."],
  [95, "C04:email-sending-receiving-managing", 1, "C",
    "SMTP bhejne ke liye; IMAP/POP3 padhne ke liye.",
    "SMTP choose kar lena."],
  [96, "C03:memory-hierarchy-memory-units", 1, "A",
    "Speed: Hard drive < RAM < Cache < Registers.",
    "Cache aur RAM ka order ulta."],
  [97, "C04:how-the-internet-works-web-browsing", 1, "B",
    "DNS = domain name → IP address.",
    "HTTP ko translation ka kaam de dena."],
  [98, "C04:email-sending-receiving-managing", 1, "B",
    "POP3 download karke server se hata deta hai; IMAP server pe rakh ke sync karta hai.",
    "POP3 ko sending protocol samajhna (wo SMTP hai)."],
  [99, "C01:sign-magnitude-1-s-2-s-complement-ranges", 1, "A",
    "MSB 1 ⇒ negative; 2's complement of 11010011 = 00101101 = 45 ⇒ −45.",
    "Unsigned 211 le lena."],
  [100, "C03:cpu-alu-cu-registers-instruction-cycle-formats", 2, "A",
    "16 − 4 = 12 address bits ⇒ 2¹² = 4096 locations.",
    "Poore 16 bits address ke liye le lena."],
  [101, "C03:cpu-alu-cu-registers-instruction-cycle-formats", 1, "B",
    "Opcode = kaunsa operation; operand = kis data pe.",
    "Opcode aur operand mix."],
  [102, "C03:memory-hierarchy-memory-units", 1, "C",
    "SSD → long-term (B), Cache → CPU–RAM buffer (D), RAM → volatile main memory (A), Registers → fastest/smallest (C).",
    "Cache aur registers ki description mix."],
  [103, "C04:how-the-internet-works-web-browsing", 1, "B",
    "Rendering engine HTML/CSS se page draw karta hai; JS engine sirf JavaScript chalata hai.",
    "JavaScript engine choose kar lena."],
  [104, "C04:how-the-internet-works-web-browsing", 1, "B",
    "Cookie = browser me rakhi chhoti text file (preferences / session).",
    "Cookie ko history ya virus samajhna."],
  [105, "C03:cpu-alu-cu-registers-instruction-cycle-formats", 1, "B",
    "PC fetch ke baad increment (I ✓); CU instruction IR me laata hai (II ✓); decode CU karta hai, ALU nahi (III ✗); registers temporary (IV ✗).",
    "ALU aur CU ka role mix."],
  [106, "C04:how-the-internet-works-web-browsing", 1, "A",
    "Browser → retrieve & display (b), URL → complete address (d), DNS → name → IP (a), HTTP → rules for exchange (c).",
    "URL aur DNS ki meaning mix."],
  [107, "C04:system-software-utilities-device-drivers-applica", 2, "B",
    "Device drivers system software hain (I ✗); OS system software (II ✓); kernel CPU/memory/hardware manage karta hai (III ✓); browser & word processor application software (IV ✗) ⇒ II aur III.",
    "Jo software user install karta hai use application samajhna (drivers system software hi hain).",
    "Response sheet ki official key A (I and IV) dikhati hai, jo dono galat statements hain — key me galti lagti hai. Verified answer B.", "A"],
  [108, "C01:sign-magnitude-1-s-2-s-complement-ranges", 2, "C",
    "9-bit 1's: −255 … +255, do zero ⇒ 511 unique values (512 nahi). 2's: −256 … +255. Max positive dono me +255 ⇒ I aur III.",
    "Bit patterns (512) aur unique values (511) ko same maan lena."],
  [109, "C01:binary-addition-subtraction-multiplication-divis", 1, "B",
    "1100 = 12, 1011 = 11 ⇒ 132 = 10000100.",
    "Shift-add me carry chhootna — decimal se check karo."],
  [110, "C02:boolean-laws-de-morgan-simplification", 2, "B",
    "(A + B)(A + C) = A + BC: (x + y′ + z′)(x + y′ + z) = x + y′; (x + y′ + z′)(x + y + z′) = x + z′; (x + y′)(x + z′) = x + y′z′.",
    "Distributive law (A + B)(A + C) = A + BC na lagana."],
  // ===== General English (paper Q21–30) =====
  [111, "E03:verbs-tenses-subject-verb-agreement", 2, "B",
    "I: neither…nor me verb paas wale subject (associates) se ⇒ 'were'. II: 'A series' singular ⇒ 'is'. IV: 'Each' ⇒ 'was'. Sirf III sahi.",
    "Beech ke plural noun ('of workshops', 'of participants') se verb choose karna."],
  [112, "E02:meaning-of-words-phrases-idioms-one-word-substit", 1, "D",
    "carried out, turned down, came across, called off — chaaron sahi use.",
    "'Came across' ko sirf 'mila (person)' samajhna."],
  [113, "E02:meaning-of-words-phrases-idioms-one-word-substit", 1, "A",
    "Conduct a study, refute an argument, propose a theory, analyze data.",
    "Collocations (kaunsa word kiske saath) na padhna."],
  [114, "E01:reading-comprehension", 2, "C",
    "'Unlike large-scale surveys … small number of cases' ⇒ depth ⇒ rich, contextualised insights.",
    "Connector (Hence / Nevertheless) aur logic match na karna."],
  [115, "E02:synonyms", 1, "B",
    "Brevity = conciseness (thode shabdon me baat).",
    "'Wit' dekh ke humour choose karna."],
  [116, "E03:verbs-tenses-subject-verb-agreement", 1, "C",
    "Do past events: pehle wala past perfect (had deteriorated), baad wala simple past (replaced).",
    "Present aur past mix karna."],
  [117, "E03:sentence-forms-active-passive-direct-indirect-se", 2, "D",
    "heavy grocery bag = noun phrase; quite quickly = adverbial; under the doormat = prepositional; a bit nervous = adjectival.",
    "Prepositional phrase ko adjectival bolna (function vs type)."],
  [118, "E02:synonyms", 1, "D",
    "Anthropo = human, -genic = produced by ⇒ human-induced.",
    "Root words na jaanna — word formation se guess karo."],
  [119, "E01:reading-comprehension", 2, "D",
    "Main idea: dark energy expansion ko accelerate kar rahi hai — weak lensing se, 1000 hrs / 600 orbits.",
    "Details (A) ya technique (C) ko main idea samajhna."],
  [120, "E03:error-spotting-sentence-improvement-fill-in-the-", 1, "D",
    "Corroborate = support/confirm (a theory). Collude = secretly conspire.",
    "Milte-julte words (collaborate / collude / corroborate) mix."],
];

const PYQ_2026_SECTIONS = [
  { id: "M", name: "Mathematics", from: 1, to: 50, offset: 0 },
  { id: "R", name: "Analytical Ability & Logical Reasoning", from: 51, to: 90, offset: 50 },
  { id: "C", name: "Computer Awareness", from: 91, to: 110, offset: 90 },
  { id: "E", name: "General English", from: 111, to: 120, offset: 90 },
];

const PYQ_2026 = {
  year: 2026,
  date: "2026-06-06",
  label: "NIMCET 2026",
  source: "Official CBT paper (response sheet), 120 questions; answers re-solved and verified",
  qs: PYQ_2026_ROWS.map(([n, leaf, d, ans, key, trap, flag, off]) => {
    const sec = PYQ_2026_SECTIONS.find((s) => n >= s.from && n <= s.to);
    return { n, leaf, d, ans, key, trap, flag: flag || "", off: off || "", sec: sec.id, paperQ: n - sec.offset, secName: sec.name };
  }),
};

// Questions per subtopic in NIMCET 2026 (used for weightage, depth and the syllabus badges).
const PYQ_COUNTS = {};
for (const q of PYQ_2026.qs) {
  const c = (PYQ_COUNTS[q.leaf] = PYQ_COUNTS[q.leaf] || { n: 0, d: 0, refs: [] });
  c.n++;
  c.d = Math.max(c.d, q.d);
  c.refs.push(q.n);
}
