/*
 * NIMCET 2025 (8 June 2025) — actual paper, all 120 questions.
 *
 * Images in pyq/2025/q<n>.webp are re-assembled from the response sheet's own
 * question/option images, without answer ticks, candidate details or watermark.
 * Every official-key answer was re-solved (all agree); `flag` notes flawed or
 * ambiguous questions. Questions outside the revised 2026 syllabus have
 * leaf = null and an `oos` label — they appear in the "Out of syllabus" set.
 *
 * Row: [n (1–120), leaf id | null, depth asked (1–3), ans, key idea, common trap, flag?, off?, oos?]
 */
const PYQ_2025_ROWS = [
  // ===== Mathematics (paper Q1–50) =====
  [1, "M07:general-solutions-of-trig-equations", 1, "B",
    "cot θ + tan θ = 1/(sin θ cos θ) = 2/sin 2θ = 2 ⇒ sin 2θ = 1 ⇒ θ = nπ + π/4.",
    "sin 2θ = 1 ka general solution 2θ = 2nπ + π/2 (nπ nahi) — divide by 2 dhyan se."],
  [2, "M09:maxima-minima", 2, "D",
    "y′ = (1 − x² sec²x)/(1 + x tan x)² = 0 ⇒ x² = cos²x; maxima x = cos x pe.",
    "Quotient rule me x·sec²x term chhoot jana."],
  [3, "M05:independent-events", 2, "C",
    "16 outcomes: P(A) = 12/16, P(B) = 6/16, P(A∩B) = 3/16 (≠ 1/4). P(A)P(B) = 9/32 ≠ 3/16 ⇒ dependent.",
    "A∩B ke outcomes ginne me (x ≥ 2, y > x) galti — list banao."],
  [4, "M02:forming-equations-transformed-roots", 3, "A",
    "u = α(α² + 1): uv = b(b² + a² − 2b + 1); u + v = α³ + β³ + α + β = −(a³ + a − 3ab) ⇒ uv·x² − (u+v)x + 1 = 0.",
    "α³ + β³ = (α+β)³ − 3αβ(α+β) ka sign galat."],
  [5, "M05:sample-space-classical-probability", 1, "B",
    "Saath khade: 2 · 4! / 5! = 2/5.",
    "India–Australia ko block banake 2! se multiply karna bhool jaana."],
  [6, "M01:composition-inverse-of-functions", 2, "A",
    "h = sgn(g(x)) jaha g defined hai waha defined ⇒ domain same. Isliye (A) galat statement hai.",
    "'NOT true' wale question me sahi statement choose kar lena."],
  [7, "M05:total-probability-bayes-theorem", 1, "A",
    "P(H) = ½·0.99 + ½·0.01 = 0.5.",
    "Sirf ek coin ki probability le lena."],
  [8, "M07:sum-product-transformations", 2, "C",
    "sin x + sin(x+1) = 2 sin(x + ½) cos ½ ⇒ max = 2 cos ½ ⇒ k = 2.",
    "Sum-to-product formula ka ½ bhool jaana."],
  [9, "M11:variance-standard-deviation-incl-origin-scale-ch", 1, "A",
    "Variance ki unit observation ki unit ka square hoti hai ⇒ (A) galat. SD ≥ MD, SD scale se badalta hai, Σ(x − a)² min at a = mean.",
    "Variance aur SD ki units mix karna."],
  [10, "M11:mean-arithmetic-weighted-combined", 1, "D",
    "Combined mean = (40·5.15 + 20·5.66)/60 = 319.2/60 = 5.32.",
    "Simple average (5.405) le lena — weights lagao."],
  [11, "M02:log-properties-change-of-base", 2, "B",
    "8^(x−1) = (¼)^x ⇒ x = 3/5. 1/(log_(x+1)4 − log_(x+1)5) = log_(4/5)(x+1); sum = log_(4/5)(1 − x²) = log_(4/5)(16/25) = 2.",
    "Change of base ulta lagana; 1/log_a b = log_b a."],
  [12, "M08:angle-between-lines-parallel-perpendicular", 1, "A",
    "m = ½ aur 3 ⇒ tan θ = |(3 − ½)/(1 + 3/2)| = 1 ⇒ acute 45°, obtuse 3π/4.",
    "Acute angle hi answer de dena — 'obtuse' pucha hai."],
  [13, "M08:distance-from-point-to-line-between-parallel-lin", 2, "C",
    "A(4,0), B(0,2), M(2,1); M′ = image in x + y = 1 = (0, −1). P: x + y = 1 aur AB ka perpendicular bisector y = 2x − 3 ⇒ P(4/3, −1/3). M′P = 2√5/3.",
    "Image formula me −2(ax₁ + by₁ + c)/(a² + b²) ka 2 bhool jaana."],
  [14, "M06:evaluation-properties-of-determinants", 2, "B",
    "Cube roots 3, 3ω, 3ω² ⇒ x + y + z = 0. Circulant det = −(x³ + y³ + z³ − 3xyz) = −(x+y+z)(…) = 0.",
    "Pura determinant expand karna — x + y + z = 0 dekho."],
  [15, null, 2, "A",
    "Vectors (2026 syllabus se hata). a·(a × b) = 0 hamesha hota hai.",
    "—",
    "Question flawed: a × b = c ho to a·c = 0 hi hoga, 2 nahi. Official key A.", "", "Vectors"],
  [16, "M02:log-equations-inequalities", 2, "C",
    "t = log₅x: t(8t − 24) = −4 ⇒ 2t² − 6t + 1 = 0 ⇒ t₁ + t₂ = 3 ⇒ product of x = 5³ = 125.",
    "Product of x = 5^(t₁ + t₂), 5^(t₁t₂) nahi."],
  [17, "M09:area-under-curves", 1, "B",
    "Symmetry: 2∫₀^(π/4)(cos x − sin x) dx = 2(√2 − 1).",
    "Poore [0, π/2] pe (cos − sin) integrate karna (0 aata hai)."],
  [18, "M01:cartesian-product-cardinality", 1, "D",
    "y = 2x − 7 ∈ [1, 20] ⇒ 4 ≤ x ≤ 13 ⇒ 10 pairs.",
    "x ki range ke saath y ki range check na karna."],
  [19, "M08:standard-general-equation-of-circle", 2, "D",
    "Centre (3, 5), r = 2. Image in 3x + y = 2: (−4.2, 2.6) ⇒ α = 8.4, β = −5.2, γ = 4.2² + 2.6² − 4 = 20.4 ⇒ ⌊23.6⌋ = 23.",
    "γ me r² minus karna bhool jaana."],
  [20, "M07:heights-distances", 3, "C",
    "AB = h/sin 2α, BC = h sin α/(sin 2α sin 3α) ⇒ AB/BC = sin 3α/sin α = 1 + 2cos 2α.",
    "cot A − cot B = sin(B − A)/(sin A sin B) identity na use karna."],
  [21, "M06:inverse-of-a-matrix", 3, "D",
    "C = (B + 2I)(A + 2I). A² + 5A + 6I = I ⇒ (A + 2I)⁻¹ = A + 3I; B² + 3B + 2I = I ⇒ (B + 2I)⁻¹ = B + I. C⁻¹ = (A + 3I)(B + I).",
    "(XY)⁻¹ = Y⁻¹X⁻¹ ka order ulta."],
  [22, "M07:sum-product-transformations", 3, "D",
    "cos50 = sin40, cos70 = sin20 ⇒ product = ¼ cos³10° sin 40° ≈ 0.1535 = α + (√3/16)cos 10° ⇒ α = 3/64 ⇒ 3/α = 64.",
    "Complementary angles (cos 50 = sin 40) na dekhna."],
  [23, null, 1, "D",
    "2a − b + 3c = (3, −3, 2), magnitude √22 ⇒ wahi vector.",
    "—", "", "", "Vectors"],
  [24, "M09:definite-integrals-properties", 2, "A",
    "Leibniz: d/dx ∫_(u)^(v) f = f(v)v′ − f(u)u′. x = π pe: e⁰·2cos π − (lower term 0) = −2.",
    "Lower limit ka derivative minus karna bhool jaana.",
    "Answer −2 tab aata hai jab lower limit 'sin x²' ko sin²x padha jaye (derivative 0 at π). Official key A."],
  [25, null, 1, "B",
    "|b|² = 4 + λ² + 4λ(a·c) = 16, a·c = ¼ ⇒ λ² + λ − 12 = 0 ⇒ λ = 3.",
    "—", "", "", "Vectors"],
  [26, "M08:parabola-standard-forms-focus-directrix-latus-re", 2, "D",
    "Vertices (t², ±t) with t/t² = tan 30° ⇒ t = √3 ⇒ (3, ±√3); centroid (2, 0).",
    "Equilateral ka 30° (axis ke saath) na lena."],
  [27, null, 1, "A",
    "Z = (X − 500)/100: P(450 < X < 500) = P(−0.5 < Z < 0) = 0.691 − 0.5 = 0.191.",
    "—", "", "", "Normal distribution"],
  [28, "M09:continuity-differentiability", 2, "C",
    "|x^α sin(1/x^β)| ≤ |x|^α → 0 jab α > 0 (β kuch bhi) ⇒ continuous. Differentiable ke liye α > 1 chahiye.",
    "Continuity ke liye β > 0 bhi zaroori maan lena."],
  [29, "M08:hyperbola-standard-form-e-asymptotes-rectangular", 3, "C",
    "M = (c, b²/a). OH/OF₂ = sin of line angle = m/√(1 + m²), m = (e² − 1)/(2e). λ ∈ (2/5, 3/5) ⇒ e ∈ (√(7/3), 2).",
    "λ ko seedha slope maan lena."],
  [30, "M08:standard-general-equation-of-circle", 1, "A",
    "Centre (r, r): |r − r − 2|/√2 = r ⇒ r = √2 ⇒ area 2π.",
    "Distance formula me √2 bhool jaana."],
  [31, null, 1, "D",
    "Projection = a·b/|b| = 1/3.",
    "—", "", "", "Vectors"],
  [32, "M05:independent-events", 1, "A",
    "P(E) = P(E|F) ⟺ independent ⟺ Eᶜ, F independent ⟺ P(F) = P(F|E). (A) me '≠' hai ⇒ equivalent nahi.",
    "'NOT equivalent' wale me equivalent option choose karna."],
  [33, null, 1, "D",
    "|a − b|² = 2(|a|² + |b|²) − |a + b|² = 50 − 1 = 49 ⇒ 7.",
    "—", "", "", "Vectors"],
  [34, "M07:heights-distances", 1, "A",
    "Second point se depression 60° ⇒ horizontal distance = h cot 60°.",
    "Pehli (30°) info me ulajh jaana — wo extra hai."],
  [35, "M04:permutations-repetition-identical-objects", 2, "C",
    "Digit sum 3 se divisible: har set me residue 0, 1, 2 ka ek-ek digit ⇒ 8 sets; last digit even ⇒ total 24.",
    "Even last digit ki condition bhool jaana."],
  [36, "M04:permutations-repetition-identical-objects", 1, "B",
    "ANGLE ek block + B, O, R ⇒ 4 units ⇒ 4! = 24.",
    "Block ke andar bhi arrange kar dena — 'ANGLE' fixed string hai."],
  [37, null, 1, "A",
    "[a b c] = 7λ − 9 = 5 ⇒ λ = 2.",
    "—", "", "", "Vectors"],
  [38, "M07:heights-distances", 1, "C",
    "d = H (45°), H − 8 = H/√3 ⇒ H = 4(3 + √3) = d.",
    "Diagram na banana."],
  [39, "M01:set-operations-symmetric-difference-venn-diagram", 2, "C",
    "Even 100–998: 450. Minus multiples of 6 (150) aur 10 (90), plus 30 (30) ⇒ 240.",
    "Inclusion–exclusion me 30 ke multiples wapas na jodna."],
  [40, "M09:standard-limits-algebraic-limits", 1, "B",
    "t = 1/(x + 1) → 0: −(e^t − 1)/t → −1.",
    "∞ · 0 form ko 0 maan lena."],
  [41, "M03:ap-nth-term-sum", 3, "B",
    "t₁, t₄, …, t₅₅ (19 terms): 19(a + 27d) = 1197; 4a + 69d = 174 ⇒ d = 2, a = 9. Σ t² (9, 11, …, 25) = 2841 = 947·3.",
    "Sub-AP ke terms ki ginti (19) galat."],
  [42, "M07:heights-distances", 1, "B",
    "Ground distance = 4000/√3; doosra plane = (4000/√3)·(1/√3) = 4000/3 ⇒ difference 8000/3.",
    "Dono angles ek hi plane pe laga dena."],
  [43, "M04:remainder-divisibility-using-binomial", 2, "C",
    "5ⁿ = (1 + 4)ⁿ = 1 + 4n + 16(…) ⇒ 5ⁿ − 4n − 1 hamesha 16 ka multiple ⇒ A ⊂ B.",
    "n = 1 pe 0 aata hai — 16(n − 1) me bhi 0 hai."],
  [44, "M04:fundamental-principle-of-counting", 1, "B",
    "Pehla digit 0 nahi: 4 × 5 × 5 = 100.",
    "Leading zero allow kar dena (125)."],
  [45, "M07:maximum-minimum-of-trig-expressions", 1, "A",
    "c = cos²y: B = 1 − c + c² ⇒ min ¾ (c = ½), max 1.",
    "sin² + cos⁴ ko 1 maan lena."],
  [46, "M09:tangents-normals", 1, "D",
    "(2, −1) ⇒ t = 2. dy/dx = (4t − 2)/(2t + 3) = 6/7 ⇒ normal slope −7/6.",
    "Tangent ka slope hi normal ka bol dena."],
  [47, "M02:sum-product-of-roots-symmetric-functions", 2, "B",
    "xy = −½; Sₙ = Sₙ₋₁ + ½Sₙ₋₂: S₃ = 5/2, S₄ = 7/2, S₅ = 19/4 = A; N = 2 ⇒ AN = 19/2.",
    "Solution pairs (x, y) aur (y, x) dono na ginna."],
  [48, null, 1, "B",
    "Poisson P(X = k) = e^(−λ) λᵏ/k!.",
    "—",
    "Mean 2/week ⇒ 2 weeks me λ = 4 ⇒ P = (32/3)e⁻⁴. ke⁻⁶ form tab aata hai jab λ = 6 ⇒ k = 36. Official key B.", "", "Poisson distribution"],
  [49, "M06:special-matrices-orthogonal-idempotent-nilpotent", 3, "A",
    "B = −I + N, N² ≠ 0, N³ = 0 ⇒ B¹⁹ = −(I − 19N + 171N²). Entries ka sum: −(3 − 0 + 171) = −174.",
    "B¹⁹ ko seedha multiply karna — nilpotent part + binomial use karo."],
  [50, "M09:definite-integrals-properties", 2, "A",
    "d/dx[sin x/(2 + cos x)] = (1 + 2cos x)/(2 + cos x)² ⇒ integral = ½ ∈ (0, 1).",
    "Options ki range se andaza na lagana — reverse derivative dekho."],
  // ===== Analytical Ability & Logical Reasoning (paper Q1–40) =====
  [51, "R01:number-series", 1, "A", "Squares: 2², 3², 4², 5², 6², 7² ⇒ 36.", "—"],
  [52, "R01:number-series", 2, "D",
    "Har row: a, a×k, a×k + k (k = 4, 5, 6, 7). Row 4: 240, 1680, 1687.",
    "Rows ke beech ka link (pichli row ka 2nd term) miss karna."],
  [53, "R04:critical-reasoning-strengthen-weaken-inference", 2, "B",
    "X sach ⇒ Y jhooth ⇒ truth-tellers ≠ 1 ⇒ Z truth-teller. X jhooth ⇒ Y sach ⇒ sirf Y truth-teller ⇒ Z trickster. Dono possible.",
    "Sirf ek case try karna."],
  [54, "R04:critical-reasoning-strengthen-weaken-inference", 1, "D",
    "Casual, relaxed group meet-up = coworkers ka quick drink.",
    "Scheduled (book club) ya formal invites ko informal maan lena."],
  [55, "M07:heights-distances", 1, "C",
    "100 cot 30° + 100 cot 45° = 173.2 + 100 ≈ 273 m.",
    "Ships ek hi taraf maan lena (difference le lena)."],
  [56, "R04:syllogism", 1, "A",
    "All apples ⊂ fruits ⊂ tasty ⇒ all apples tasty, aur some tasty things are apples.",
    "Conversion (II) ko invalid samajhna."],
  [57, "R06:time-speed-distance-trains-boats", 1, "B",
    "Net 10 ft/hour; 90 ft ke baad last climb 30 ft se 120 tak.",
    "Last ghante me slip nahi hota — wo bhool jaana.",
    "'Beginning of each hour' climb pe 5 pm aata hai; climb poore ghante chale to 6 pm. Official key B (6 pm)."],
  [58, "R04:syllogism", 1, "A",
    "Cakes ⊂ ice cream, ice cream ∩ chocolate = ∅ ⇒ no cake is chocolate.",
    "I aur II ko complementary pair samajhna."],
  [59, "R04:syllogism", 1, "C",
    "Some great, some wise — 'all men either' ya 'some neither' dono definite nahi.",
    "Possibility ko conclusion maan lena."],
  [60, "R06:number-system-divisibility-hcf-lcm-remainders-un", 2, "A",
    "a = 630/n + 3(n − 1)/2 integer hona chahiye: n = 6 ⇒ 105 + 7.5 ✗.",
    "Har option daal ke check na karna."],
  [61, "R02:direction-sense-distance", 1, "B",
    "Net: 2 km North, 7 km East ⇒ √53 ≈ 7.28 km.",
    "Right/left ke baad direction galat lena.",
    "Calculation se 7.28 km aata hai jo kisi option me nahi; official key 7.62 km (B)."],
  [62, "M05:sample-space-classical-probability", 1, "A",
    "Neither red nor green = blue = 7/21 = 1/3.",
    "Complement me galti."],
  [63, "R06:ratio-proportion-ages", 1, "D",
    "R − 10 = 2(S − 10), 2(R + 10) = 3(S + 10) ⇒ S = 30, R = 50.",
    "10 saal pehle/baad dono pe na lagana."],
  [64, "R03:linear-seating-arrangement", 1, "A",
    "A–D–E (left→right) + B A ke paas, C end pe ⇒ B A D E C ⇒ 2nd = A.",
    "C ko galat end pe rakhna."],
  [65, "R06:percentages", 1, "D", "1.3 × 0.8 = 1.04 ⇒ 4% increase.", "30 − 20 = 10% bol dena."],
  [66, "R05:counting-figures-triangles-squares", 2, "D",
    "Systematic counting: chhote triangles → do milake → bade.",
    "Overlapping triangles chhoot jana."],
  [67, "R06:ratio-proportion-ages", 1, "C",
    "D(2D − 4) = 240 ⇒ D = 12 ⇒ 2 saal pehle 10.",
    "Present age hi answer bol dena."],
  [68, "R04:statements-conclusions-assumptions-arguments", 2, "B",
    "Rainfall forecast aur GDP revision ke alag-alag kaaran hain.",
    "Monsoon → GDP link maan ke cause–effect bana dena."],
  [69, "R04:critical-reasoning-strengthen-weaken-inference", 2, "C",
    "Price AVC se upar ⇒ loss kam hota hai aur fixed cost kuch recover hoti hai ⇒ (a), (c).",
    "Dumping ko profit maximisation samajhna."],
  [70, "R06:percentages", 1, "D", "0.95 × 1.05 = 0.9975 ⇒ 0.25% decrease.", "'Barabar change = no change' maan lena."],
  [71, "R06:number-system-divisibility-hcf-lcm-remainders-un", 2, "A",
    "1–9: 9 digits, 10–99: 180 ⇒ 189. 2028 − 189 = 1839 = 3 × 613 ⇒ 712 ka last digit 2 ⇒ closest 1.",
    "2-digit numbers ke digits (180) ginna bhool jaana."],
  [72, "R01:number-series", 1, "D", "n(n + 1): 1·2, 2·3, …, 6·7 = 42.", "—"],
  [73, "R06:percentages", 1, "C", "161/1.15 = 140.", "161 ka 15% minus karna."],
  [74, "R01:number-series", 2, "B",
    "Series: ×2±1, ×3±2, ×4±3 (alternate +/−) ⇒ 267, 1823, 6759.",
    "Ek series ka pattern teeno pe laga dena."],
  [75, "R06:number-system-divisibility-hcf-lcm-remainders-un", 1, "B",
    "Digits ka product 12 aur +36 se ulta ⇒ 26 → 62.",
    "Options check na karna."],
  [76, "R06:simple-compound-interest", 2, "C",
    "2x · (1.2² − 1) = 0.88x = 5x · 2r/100 ⇒ r = 8.8%.",
    "CI aur SI ke formulas mix."],
  [77, "R03:linear-seating-arrangement", 1, "D", "Q P R S ⇒ front Q.", "—"],
  [78, "R04:critical-reasoning-strengthen-weaken-inference", 2, "C",
    "X akela height badhata hai, X + Z me koi farak nahi ⇒ Z, X ka effect rokta hai.",
    "Plot 4 ko dekh ke Z ko neutral bol dena."],
  [79, "R06:time-work-pipes-cisterns", 1, "B",
    "1 man = 2 women ⇒ kaam = 80 woman-days.",
    "Men ko women me convert na karna.",
    "Question adhoora hai ('3 men and women' — kitni women nahi likha). Official key 4 days (B)."],
  [80, "R02:letter-number-shifting-substitution-coding", 2, "C",
    "−1, +2, −3, +4 pattern: S→R, T→V, A→X (wrap), R→V ⇒ RVXV.",
    "Alphabet wrap-around (A − 3 = X) bhool jaana."],
  [81, "R02:blood-relations-direct-puzzle-coded", 1, "A",
    "Mother's father's granddaughter ⇒ John ki behen (ya cousin).",
    "—",
    "Strictly 'sister' aur 'cousin' dono possible; official key Sister (A)."],
  [82, "R01:classification-odd-one-out", 1, "B", "Incubating, promoting, nurturing = growth; pampering alag.", "—"],
  [83, "R01:number-series", 1, "C", "×2, ×3, ×4, ×3, ×2 ⇒ 216.", "Pattern ko ×5 maan lena."],
  [84, "R03:floor-box-scheduling-attribute-puzzles", 2, "B",
    "Received: Chirag 3 (Anand ×2, Dinesh 1), Beena 2, Elango 2, Anand 1, Dinesh 1.",
    "Reply-all ke recipients galat ginna."],
  [85, "R05:calendars-day-of-week-odd-days", 1, "A", "2022 non-leap ⇒ +1 day ⇒ Sunday.", "—"],
  [86, "R02:letter-number-shifting-substitution-coding", 2, "B",
    "+2, −1, +3, −2, +4, −3 ⇒ PRAYER → RQDWIO.",
    "Pattern ko sirf ek letter pe check karna."],
  [87, "R04:syllogism", 1, "B", "All engineers good at math ⇒ some good-at-math are engineers.", "Conversion 'all' me na karna."],
  [88, "R03:floor-box-scheduling-attribute-puzzles", 3, "B",
    "Swift: B, G. Creta: A, F + D (C sisters ke saath nahi). A teacher ⇒ F engineer (same profession saath nahi).",
    "Profession constraint (iv) bhool jaana."],
  [89, "R02:blood-relations-direct-puzzle-coded", 1, "B", "Sister's brother = Mohan ⇒ Sarita = mother.", "—"],
  [90, "R04:syllogism", 2, "B",
    "Teachers are graduates ⇒ not poor; poets poor ⇒ not teachers; some mathematicians poets ⇒ not teachers. 'Some teachers are not mathematicians' derive nahi hota.",
    "Har option ko statements se derive karke dekho.",
    "Paper me question line ('which does not follow') chhoot gayi hai; official key B."],
  // ===== Computer Awareness (paper Q1–20) =====
  [91, "C01:binary-octal-hex-decimal-conversions-integers", 1, "D", "265 = 256 + 9 = 0x109.", "Binary ko hex likh dena."],
  [92, "C01:representation-of-characters-ascii-unicode-bcd", 1, "A", "Unicode ke pehle 128 code points = ASCII.", "—"],
  [93, "C01:overflow-detection", 2, "B",
    "A = −103, B = −41 ⇒ −144 < −128 ⇒ overflow (do negative ka sum positive bit dikhata hai).",
    "Carry ignore karke result likh dena."],
  [94, "C04:system-software-utilities-device-drivers-applica", 1, "D",
    "Debugger: breakpoints, step execution, registers dekhna. Compiler = object code, linker = executable.",
    "Compiler/linker ka kaam debugger ko dena."],
  [95, null, 2, "D",
    "Mask ((1 << m) − 1) << p ke saath XOR toggle karta hai.",
    "—", "", "", "C programming (bit manipulation)"],
  [96, null, 2, "A",
    "Instruction TLB fetch stage me, data TLB memory stage me.",
    "—", "", "", "Pipelining / TLB (computer architecture)"],
  [97, null, 2, "A",
    "IR → code generation, top-down parsing → leftmost derivation, runtime → activation records, register allocation → graph colouring.",
    "—", "", "", "Compiler design"],
  [98, "C03:cpu-alu-cu-registers-instruction-cycle-formats", 3, "C",
    "512 KB = 2¹⁹ ⇒ address 19 bits; 6 registers ⇒ 3 bits × 2 = 6; opcode = 32 − 25 = 7 ⇒ 128 instructions.",
    "Register field ko ek hi baar ginna."],
  [99, "C02:boolean-laws-de-morgan-simplification", 1, "D", "De Morgan: ((A + B)·C)′ = A′B′ + C′.", "Sirf ek level De Morgan lagana."],
  [100, "C01:sign-magnitude-1-s-2-s-complement-ranges", 1, "A", "9-bit: 1's min −255, 2's min −256.", "—"],
  [101, "C01:fractional-number-conversions", 1, "B", "10101 = 21; .10101 = ½ + ⅛ + 1/32 = 0.65625 ⇒ 21.65625.", "Fraction bits ke weights (2⁻¹, 2⁻², …) galat."],
  [102, "C02:boolean-laws-de-morgan-simplification", 2, "D",
    "(A + BC′)(A′B + C) = AC + A′BC′ (AA′ = 0, C′C = 0).",
    "Expand karte waqt cross terms chhootna."],
  [103, null, 2, "C",
    "Hardwired fast; horizontal microcode me har signal ka bit; vertical microcode chhota word, kam parallelism (III galat).",
    "—", "", "", "Control unit design (microprogramming)"],
  [104, "C02:logic-gates-universal-gates", 1, "B", "XOR = 1 jab inputs alag hon.", "XNOR se mix."],
  [105, "C02:boolean-laws-de-morgan-simplification", 1, "A", "A = 1, B = 0: A⊕B = 1; B → C = 1 ⇒ true.", "B → C me B = 0 pe true hota hai — bhool jaana."],
  [106, "M01:set-operations-symmetric-difference-venn-diagram", 2, "D",
    "Mountain ya river = R ∪ M; desert nahi = ∩ Dᶜ ⇒ (R ∪ M) ∩ Dᶜ.",
    "'Either … or' ko exclusive (R∆M) samajhna."],
  [107, "C03:memory-hierarchy-memory-units", 1, "A",
    "DRAM capacitor ⇒ refresh; SRAM flip-flop ⇒ no refresh; SRAM DRAM se fast; DRAM dense ⇒ main memory.",
    "DRAM ko faster samajhna."],
  [108, null, 2, "A",
    "Interrupt-driven I/O CPU-bound load me CPU free karta hai; I/O-bound me programmed I/O ka overhead kam.",
    "—", "", "", "I/O organisation (interrupt vs programmed I/O)"],
  [109, "C03:memory-hierarchy-memory-units", 1, "B", "CPU ↔ word, cache ↔ block, memory ↔ page.", "Block aur page ulte."],
  [110, "C03:input-output-storage-backup-devices", 1, "C", "SSD (no moving parts) sabse fast.", "HDD choose karna."],
  // ===== General English (paper Q21–30) =====
  [111, "E02:synonyms", 1, "B", "Belligerent = hostile, aggressive.", "Bellyful se sound match."],
  [112, "E03:verbs-tenses-subject-verb-agreement", 1, "A", "'One of the employees' ⇒ singular 'is'.", "Employees dekh ke 'are'."],
  [113, "E03:verbs-tenses-subject-verb-agreement", 1, "A", "lay (rakhna) – laid – laid; lie (letna) – lay – lain.", "Lay aur lie mix."],
  [114, "E03:verbs-tenses-subject-verb-agreement", 1, "C", "'The man and the dog' plural ⇒ 'were fleeing'.", "'Flees' (singular)."],
  [115, "E03:articles-prepositions", 1, "D", "Article sound se: 'an MBA' (em), 'a mathematical' (m).", "Spelling (vowel letter) se article choose karna."],
  [116, "E02:meaning-of-words-phrases-idioms-one-word-substit", 1, "A", "Cost an arm and a leg = bahut mehnga.", "—"],
  [117, "E02:antonyms", 1, "D", "Tacit = unspoken ⇒ antonym unequivocal / explicit.", "Implicit (synonym) choose karna."],
  [118, "E02:meaning-of-words-phrases-idioms-one-word-substit", 1, "A", "Hit the sack = sone jaana.", "—"],
  [119, "E03:articles-prepositions", 1, "B", "City ke saath 'in Rio de Janeiro', 'on' nahi.", "—"],
  [120, "E03:verbs-tenses-subject-verb-agreement", 1, "A", "'Understand' stative verb ⇒ continuous me nahi: 'They understand'.", "Stative verbs (know, understand, believe) ko -ing me lena."],
];
